### ISSUE TITLE
symbolic icons for headerbar

### ISSUE THREAD

**Issue by FalkAlexander** [Alecaddd/sequeler#101]
please provide an option in settings for using symbolic icons in the headerbar for better integration with the adwaita (gnome default) theme

**Comment by Alecaddd** [comment]
Can you send me a screenshot of how it looks currently in Adwaita?
I will consider adding that option.
Cheers

**Comment by falkse** [comment]
![colored](https://user-images.githubusercontent.com/5732964/38146508-94d51ece-344e-11e8-8727-00661c10fac8.png)
This is how the headerbar looks currently with Adwaita
