### ISSUE TITLE
password hashing

### ISSUE THREAD

**Issue by FalkAlexander** [Alecaddd/sequeler#102]
sequeler saves the password as clear text into the dconf key: com.github.alecaddd.sequeler saved-connections
dconf is accessible as normal user, password hashing would increase the security

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
This is a feature I want to add, but not being an expert on this, I'm not 100% sure how to encrypt/decrypt passwords properly when connecting to the database.
The connection requires a plain password, not hashed.
Do you have any info or guide I could read?

**Comment by falkse** [comment]
I have no experience with Vala and GLib, sorry.

**Comment by bilelmoussaoui** [comment]
You shouldn't be saving any sensitive information on dconf anyway. The best way to handle this is to save those passwords using libsecret

**Comment by Alecaddd** [comment]
@bilelmoussaoui oh nice, do you have any examples or apps that use this library?

**Comment by bilelmoussaoui** [comment]
https://developer.gnome.org/libsecret/unstable/vala-examples.html

**Comment by Alecaddd** [comment]
You guys should be happy to know that I successfully implemented this feature and it's currently backed in the `dev` branch.
I'm currently implementing and upgrading feature that'll run under the hood on startup to remove the passwords currently stored with GSettings and store them property.

Thanks for the suggestion about libsecret
