### ISSUE TITLE
`.pot` and `.po`s outdated

### ISSUE THREAD

**Issue by PeterNerlich** [Alecaddd/sequeler#105]
I discovered that the `.pot` and consequently all `.po` files are outdated, while the code also does not consistently use the translation function `_()`.

The target `pot` of `build/CMakeFiles/Makefile2` is not automatically run on build. I just started having a look at CMake and the build process suggestion by Elementary so I don't have in-depth knowledge of how to achieve this, but I saw another project that also intelligently updated all `.po` files with the new strings.

**Comment by Alecaddd** [comment]
I'm currently switching build system from `CMake` to `meson`.
After that, I'll trigger an update for the language files.
Thanks for the report.
Cheers

**Comment by Alecaddd** [comment]
I just pushed to `master` the new meson build system with the refreshed language files.
Happy translating :smile:
