### ISSUE TITLE
Cannot connect to local Postgres instance

### ISSUE THREAD

**Issue by ziggy42** [Alecaddd/sequeler#106]
I have a local instance of postgres that I can access without problems from IntelliJ, but not with sequeler:

![screenshot from 2018-04-05 16-18-14](https://user-images.githubusercontent.com/4258550/38371565-09c7e570-38ed-11e8-8c39-38ee9038ff8c.png)

OS: Fedora 27
App installed from flathub

**Comment by Alecaddd** [comment]
Shouldn't the local port of PostgreSQL be `5432`? Did you add the `0`?
If IntelliJ works for you, be sure your settings are identical.
I don't run Fedora and the flatpack is not maintained by me, so I'm not sure if this issue could be related to the distro as I'm running elementaryOS and I don't have any problem with my local PostgreSQL installation.

Cheers

**Comment by ziggy42** [comment]
Yes I'm sure I changed the port on purpose :smile:

**Comment by ziggy42** [comment]
Snap didn't work for me either (something about the desktop file) so I'm just using the rpm now. I'd leave this issue open in the case someone knows how to fix the flatpak problem.

**Comment by ziggy42** [comment]
From GNOME software I see 3 entries for sequeler: from snap, flathub and fedora repo :smile:

**Comment by Alecaddd** [comment]
Oh wow, I didn't know that, I guess Sequeler has been packaged more often than I thought 😄

**Comment by rafaelgontijo** [comment]
resolved, can close.
