### ISSUE TITLE
cannot open filedialog

### ISSUE THREAD

**Issue by gwutz** [Alecaddd/sequeler#109]
when i want to add a new Database, i cannot open the filedialog for SQlite databases.
The error message on the console:

[FATAL 14:47:05.409276] [GLib] g_variant_new_string: assertion 'string != NULL' failed

Tested with the current published flatpak version

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
I don't personally maintain the flatpak version.
Please, go to this repo and report the issue there: [](https://github.com/flathub/com.github.alecaddd.sequeler)

Cheers
