### ISSUE TITLE
Paginate Rows Option

### ISSUE THREAD

**Issue by firmantr3** [Alecaddd/sequeler#112]
Hey man, i love this app, its fast and simple. I think it would be awesome to have paginate rows option to access tables that have a lot of rows.

Thanks!

**Comment by Alecaddd** [comment]
Hi, thank you so much for using Sequeler.
A fully functional Pagination is part of the new features list for the new version 😄 
Cheers

**Comment by olymk2** [comment]
Yes really nice little app, on top of pagination it needs a limit by default like other databases do.

Basically cant be used in its current form as it kills the database server on massive data sets :/

**Comment by Alecaddd** [comment]
Built-in pagination for the Content tab will be released with the next version sometimes this weekend. The default amount of results per page is set to 1000, not editable by the user for now.
If you guys want, you can download the dev branch and compile the source to check if it works with your amount of data.
