### ISSUE TITLE
No provider 'MySQL' installed

### ISSUE THREAD

**Issue by Huholoman** [Alecaddd/sequeler#115]
Hello,
i clonned this repo, installed dependencies, builded and installed it and then I tryed to connect to my mysql docker service and it sayd

```
No provider 'MySQL' installed
```
Does anyone know, what causes this error?

Thanks!

Edit: I am running Debian Buster and I have installed default-mysql-client.

**Comment by cjfloss** [comment]
Do you have libgda-mysql installed?

**Comment by Huholoman** [comment]
Thats it! Thanks a lot

**Comment by developersharif** [comment]
libgda-mysql5 solved my problem.

**Comment by eduardomartin71** [comment]
In debia 12 after installing the dependencies mentioned, still have the "unable to connect to mysql provider" no libgda-mysql5 in debian 12.

**Comment by DarthMikke** [comment]
> In debia 12 after installing the dependencies mentioned, still have the "unable to connect to mysql provider" no libgda-mysql5 in debian 12.

On Debian the package names are somewhat different. This command fixed the issue for me:

```console
$ sudo apt install libgda-5.0-mysql libgda-5.0-postgres
```
