### ISSUE TITLE
Improve the selected DB contrast

### ISSUE THREAD

**Issue by btd1337** [Alecaddd/sequeler#116]
Currently the label that displays the selected database has a color that doesn't contrast with the background.

A new color it's recommended.

I'm using the default elementary gtk theme.

![captura de tela de 2018-05-24 15-05-13](https://user-images.githubusercontent.com/11943860/40503343-21a16d7c-5f64-11e8-8184-34c7638d2eee.png)

**Comment by Alecaddd** [comment]
Mh, that's weird, I can't reproduce this issue.
Are you sure your Gtk Theme wasn't changed at all? I see some extra icons in the titlebar and I wonder if some tweaks you made are causing that issue.

**Comment by btd1337** [comment]
I'm using elementary OS Juno, default themes.

How to reproduce:
1º Open Sequeler
2º Click on a saved database

![tela1](https://user-images.githubusercontent.com/11943860/40623270-5e9c361a-627c-11e8-86dd-82dc98d65e51.png)

![tela2](https://user-images.githubusercontent.com/11943860/40623273-648f23a2-627c-11e8-8972-7dee81fcf2d5.png)

**Comment by Alecaddd** [comment]
Oh, you're using Juno daily build?
That makes sense. Sequeler is not optimized for Juno yet as the new Gtk stylesheet changed and broke a lot of things.
I'm setting up my computer with Juno to start porting Sequeler and fixing all these annoying things.
Thanks for the report.

**Comment by btd1337** [comment]
@Alecaddd The community that should thank you for your excellent work
