### ISSUE TITLE
Table names are sorted in descendant alphabetical order

### ISSUE THREAD

**Issue by pappfer** [Alecaddd/sequeler#117]
Is this intentional? Is there any way to change this behaviour?
![sequeler](https://user-images.githubusercontent.com/738623/40912588-4d0d332e-67f2-11e8-9f55-df380a8a7462.png)

**Comment by Alecaddd** [comment]
That is not the normal behavior as tables are listed in alphabetical A-Z order.
I see from the screenshot you're running an older version of Sequeler. Where did you install it from?
Current stable version is `0.5.4`

**Comment by pappfer** [comment]
I'm running the latest stable version, 0.5.4 on Solus. It's just got into the official repository of Solus a couple of days ago, that's where I installed it from, because the Snap package didn't work on Solus.

**Comment by Alecaddd** [comment]
Mh, I'm not the maintainer of that version, unfortunately. Someone must have packaged it and put it there. I can't test it as I don't run that distro.

**Comment by Alecaddd** [comment]
I found the developer who packaged it: https://dev.solus-project.com/p/DataDrake/
And the link tot he repo for Solus: https://dev.solus-project.com/source/sequeler/

You can submit a bug report there.
Cheers

**Comment by pappfer** [comment]
Yes, I know he packaged it, I asked him to do so. 🙂
I just wasn't aware that this is a packaging issue.

**Comment by DataDrake** [comment]
Are we sure this isn't some subtle difference in how libgda handles table listings when built against MariaDB instead of MySQL? I can't reproduce this with a Sqlite3 DB for example.

**Comment by Alecaddd** [comment]
I test Sequeler every time with all the DBs listed in the drop-down.
I can't reproduce this issue in any of them (MySql, MariaDB, PostgreSql, SQLite).
Also, Sequeler is available as FlatPak and I haven't had a reported issue like this one from Fedora users.
I'm not sure why it's happening. Could be some particular settings on the user's database?

**Comment by DataDrake** [comment]
![screenshot from 2018-06-05 18 45 16](https://user-images.githubusercontent.com/4991377/41006701-a91c0434-68f0-11e8-9b81-cc861eaa313f.png)
Verified using flatpak on Solus with MariaDB (10.1.29) running locally.

**Comment by Alecaddd** [comment]
Uh, this is really interesting.
I'm gonna reopen this issue and do some more testing on another computer other than mine.
Let's see if I can recreate the issue.

I guess, one viable solution would be to implement an A-Z sortable button in the table list.
Thanks for investigating the issue.

**Comment by Alecaddd** [comment]
Whoooooooops, I found the issue, my bad!
I'm not a smart man, I was totally sorting tables in descending order and I didn't noticed.
Will push a new version with the fix soon.
Sorry for the trouble to both.

**Comment by Alecaddd** [comment]
@DataDrake 
A new version of Sequeler is out, `v0.5.5`, which should fix all these annoying bugs.
How should we go for future updates in trying to keep in sync the version available in the Solus repository?
