### ISSUE TITLE
Structure tab displays info about other databases as well

### ISSUE THREAD

**Issue by pappfer** [Alecaddd/sequeler#118]
1. I login to one of my databases
2. Select a table
3. The Structure tab displays information about tables with the same name from other databases (outside of the current one) as well

I guess you should add some filter for the `TABLE_SCHEMA` column.

![sequeler](https://user-images.githubusercontent.com/738623/40972678-c6a0125e-68c1-11e8-8bd0-232f7fd23c6c.png)

**Comment by Alecaddd** [comment]
This was an issue in an older version of Sequeler and has been fixed since then.
I can't reproduce it with MySql or MariaDB.

**Comment by pappfer** [comment]
Same goes for the Relations tab.
