### ISSUE TITLE
Password field being ignored?

### ISSUE THREAD

**Issue by b3none** [Alecaddd/sequeler#122]
I'm trying to use this tool but for some reason whenever I put anything into the password field it gets ignored.

i.e. `(using password: NO)` even when I type in my password.

I'm using version 0.5.5.

**Comment by Alecaddd** [comment]
Did you install it from the elementary OS Appcenter, flatpack. or compiled form source?
Did you try saving the connection and then trying to connect?
Try to give me more information as possible so I can troubleshoot it.
Thanks for using Sequeler.

**Comment by Alecaddd** [comment]
I tested it and I confirmed the bug.
I'll patch it and push a new version later tomorrow evening.
Saving the connection and then connecting should be good as a temporary workaround.
Apologies for the issue
