### ISSUE TITLE
sqlite open dialog has untitled filter

### ISSUE THREAD

**Issue by btkostner** [Alecaddd/sequeler#124]
a small detail

![screenshot from 2018-06-30 10 55 06](https://user-images.githubusercontent.com/3385679/42127818-25e639dc-7c54-11e8-80f7-8a48219ac687.png)

**Comment by Alecaddd** [comment]
Oopsie, totally missed that.
Thanks for the heads up

**Comment by Alecaddd** [comment]
I can't seem to recreate this issue. Is this happening in Juno or Loki?
Does it happen when you open the dialog to pick an sqlite file for a new connection?

**Comment by Alecaddd** [comment]
Nevermind, I figured it out :smile:
