### ISSUE TITLE
Delimiters, and comments get interpreted as a syntax error

### ISSUE THREAD

**Issue by Zachs-Kappler** [Alecaddd/sequeler#125]
Originally, I've been having a problem with my stored procedures, triggers, and scheduled events with MySQL 8. I've narrowed my problem down to stuff like the DELIMITER function being interpreted as a syntax error by this client, or the server because this client is mangling it somehow. Here is a list of what I've found to be giving me trouble:

- Delimiter doesn't work no matter what character I use. (ex. DELIMITER |)
- Multi-line comments are not ignored as they should be. (ex. /* Comment */)
- Single-line comments are also not ignored. (ex. // Comment)

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
This is an issue unfortunately related to `LibGda`, the library I'm using to have shared bindings between database types, without the necessity of implementing dedicated libraries for each type (eg. MySQL, PostgreSQL, SQLite).
Unfortunately, this library is a bit outdated, and the gnome maintainers haven't released a new version in almost 3 years.
They recently revamped the project by moving it to GitLab, and I decided to wait and see if they'll be releasing a patched version soon.
If the project gets discontinued, I'll be starting the transition to implement dedicated libraries in Sequeler.
Cheers

**Comment by Alecaddd** [comment]
Hey @Zachs-Kappler, I'm working on fixing this.
In the latest commit I implemented a method that properly recognize comments and strips them away before running the raw query.

I'm trying to find a way to handle the DELIMITER attribute.
Is there any reason for not using the default `;`?

Cheers

**Comment by Zachs-Kappler** [comment]
I use delimiter for creating procedures and triggers without accidentally causing part of said code getting misinterpreted.
```
DELIMITER //
CREATE PROCEDURE Truncate_Queues()
    COMMENT 'Truncating queue tables...'
    BEGIN
      DELETE FROM queue_main;
      ALTER TABLE queue_main AUTO_INCREMENT = 1;
      DELETE FROM registered;
      ALTER TABLE registered AUTO_INCREMENT = 1;
    END;
//
DELIMITER ;
```
It's what has been drilled into my head by SQL classes and tutorials, so I assume that is the correct usage. Thanks for working on this issue!

**Comment by Alecaddd** [comment]
I'm gonna merge PR #270, which fixes the issue with comments.
For now I'm not gonna handle the DELIMITER keyword as `LibGDA` should do that, and it creates too much overhead for me.
I have this request in my backlog and I'll try to implement it in future releases.
