### ISSUE TITLE
Disproportionate icons

### ISSUE THREAD

**Issue by ghost** [Alecaddd/sequeler#126]

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
Which Distro and Gtk theme are you using?
All those icons are set with a consistent size, if the relations icon looks bigger, is probably due to your Gtk theme missing that specific px resolution.
Cheers

**Comment by Sphinxs** [comment]
Linux Mint 19 ( Tara ) Xfce and the theme Arc-Dark ( :

**Comment by Alecaddd** [comment]
Yeah, unfortunately I don't have control over that Gtk theme. I'm using built-in Gtk CSS declarations to avoid these issues and maintain the experience consistent no matter the distro, but if that Gtk theme is missing a specific icon variation, there's nothing I can do about it, sorry.
Maybe you could file an issue on the repo of that theme.

I'm glad Sequeler runs also on Linux Mint 😀

**Comment by Sphinxs** [comment]
Sequeler it's awesome, congratulations :blush: It made easier creating migrations using Sql Alchemy + Python and visualizing the registers and structure on Sequeler
