### ISSUE TITLE
[Request] Add MongoDB Support

### ISSUE THREAD

**Issue by btd1337** [Alecaddd/sequeler#133]
It would be great job if you could add MongoDB support to Sequeler!

Is this possible?

**Comment by Alecaddd** [comment]
Mh, I don't think there's currently available a binding for MongoDB in GTK, and LibGDA currently doesn't' support that Database type.
If the new version of LibGDA comes with support for that database, I will be sure to add it.

**Comment by btd1337** [comment]
Currently this is the better option: [Robo 3T](https://robomongo.org/)

**Comment by samuelcecilio** [comment]
> Friendly SQL Client

Maybe I'm wrong, but Sequeler should not support NoSQL (MongoDB, CouchDB, Redis, Cassandra). It's another universe. Try something like [Compass](https://www.mongodb.com/download-center?jmp=nav#compass) (cross-platform).

ps.: I'm sorry if I'm wrong.

**Comment by Alecaddd** [comment]
@samuelcecilio you're right, I didn't think about it and the implication of supporting NoSQL databases.

Closing this issue as suitable alternatives are available 😃
