### ISSUE TITLE
Update tables content after a query has been executed.

### ISSUE THREAD

**Issue by SkyzohKey** [Alecaddd/sequeler#137]

**Comment by Alecaddd** [comment]
I'm not gonna implement this as the Content tab is meant to show the whole content of the table.
After running a query, the results are shown in the same Query tab. Affecting the Content tab would create confusion as you don't have a direct visualization of what's causing the "filtering" of the data like in the query tab.
An upcoming feature for the Content tab is to allow the users to filter results by a built-in search form.

**Comment by SkyzohKey** [comment]
Cannot you just add pagination and update content for the current page, or at least reload the table content when we switch to the content tab. Would be way more effective than an hidden refresh button.
