### ISSUE TITLE
Authentication plugin 'caching_sha2_password' cannot be loaded: /app/lib/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mrkrishnaupadhyay** [Alecaddd/sequeler#140]

**Comment by Alecaddd** [comment]
This doesn't help at all.
Can you provide more information?
Are you running Sequeler on elementary OS? Juno or Loki?
Are you running it via flatpack? Which distro are you using?

**Comment by Alecaddd** [comment]
Closing this for lack of information
