### ISSUE TITLE
Fuzzy icon in alt tab selection on gnome shell

### ISSUE THREAD

**Issue by viseztrance** [Alecaddd/sequeler#146]
The app icon is really fuzzy in the alt tab selector on gnome shell as you can see bellow (click on the image for full size):

![alt-tab](https://user-images.githubusercontent.com/13088/44922068-3bef9480-ad3c-11e8-849d-f76a8a9b18d6.png)

However it looks sharp in the app selector:
![apps](https://user-images.githubusercontent.com/13088/44922070-3eea8500-ad3c-11e8-9952-79b740f5b845.png)

---
GNOME Shell 3.28.3
OS: Ubuntu 18.04

**Comment by Alecaddd** [comment]
Uh, that's weird, thanks for the report.
All the icons are SVGs, so I think probably Gnome is grabbing the PNG for the 128 px variation only in the app switcher. I'll remove that PNG from the icon folder and release a new version.
Let's see if it fixes it.

**Comment by viseztrance** [comment]
Thank you for replying so fast. I checked out the dev branch and unfortunately your change doesn't work.

I investigated this a bit on my own by looking over the source code of [nautilus](https://github.com/GNOME/nautilus/tree/master/data/icons/hicolor) and [gedit](https://github.com/GNOME/gedit/tree/master/data/icons/hicolor). 

It looks like this is happening because gnome expects png files in `data/assets/icons/<icon-sizes>`. 
Changing these files to pngs (and updating `meson.build`) fixed the issue on my machine.

**Comment by Alecaddd** [comment]
Did you clear the icon cache after installing the `dev` branch?
I messaged a Gnome dev and he told me that the location of the icons doesn't matter and SVGs are also used.
This is strange, I will investigate further
