### ISSUE TITLE
Flatkak file chooser is not working

### ISSUE THREAD

**Issue by ohaessler** [Alecaddd/sequeler#147]
On RHEL the file chooser is not working (for example to choose an SQLite database. Error:

flatpak run com.github.alecaddd.sequeler
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"

(Sequeler:3): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'text != NULL' failed

(Sequeler:3): Gtk-WARNING **: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

**Comment by Alecaddd** [comment]
I don't maintain the flatpak version. You should open an issue on the dedicated repository: https://github.com/flathub/com.github.alecaddd.sequeler

**Comment by bilelmoussaoui** [comment]
You need to install  `xdg-desktop-portals` too.
