### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by sscarduzio** [Alecaddd/sequeler#148]
Hi, sorry for the dumb question, but is there any build for MacOS? Or any documentation on how to get this to work in MacOS?

**Comment by jtraulle** [comment]
First try :

![capture d ecran 2018-09-08 a 18 56 48](https://user-images.githubusercontent.com/613615/45256612-28c27180-b399-11e8-8cde-fed55a73cbc4.png)

**Comment by sscarduzio** [comment]
@jtraulle cool, does it work? is it using xorg?

**Comment by jtraulle** [comment]
It launch without the need of Xorg/Quartz but for now :
- no icons
- when I try to connect to a mysql database, I get the **No provider 'MySQL installed** error

Got this error at the end of the install script :
```bash

Traceback (most recent call last):
  File "/Users/jean/Sites/sequeler/meson/post_install.py", line 19, in <module>
    subprocess.call(['update-desktop-database', '-q', desktop_database_dir])
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'update-desktop-database': 'update-desktop-database'
FAILED: meson-install 
/usr/local/opt/python/bin/python3.7 /usr/local/Cellar/meson/0.47.2/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

but this is normal because `update-desktop-database` only exists on GNU/Linux env.

**Comment by Alecaddd** [comment]
Hi, thanks for trying it out, but it doesn't exist any version compatible for MacOS.
I'm not planning to add or maintain any support for other OSs other than Linux.
Closing this issue.

Cheers

**Comment by jtraulle** [comment]
No problem, I was just curious to compile a Vala app on macOS to see if it is still usable and I am pretty impressed it worked. Apart from the icons and the libgda providers.
