### ISSUE TITLE
Feature: Create and drop databases

### ISSUE THREAD

**Issue by tdgroot** [Alecaddd/sequeler#150]

**Comment by Alecaddd** [comment]
I will try to add this in the future, but I'm not sure the current status of the `LibGda` allows the app to easily achieve this.
I will investigate

**Comment by michaelkanis** [comment]
FWIW at least with a MySQL connection you can "CREATE SCHEMA foobar;" and "DROP SCHEMA foobar;" in the queries tab and it will happily execute this.

**Comment by Alecaddd** [comment]
It's already part of the `v1.0` project and will soon be developed. I don't have a defined timeline for now

**Comment by Alecaddd** [comment]
And after only 2 years, I finally started working on this feature.
I'm so good at this >_>
