### ISSUE TITLE
Feature: Create/Save connection without default schema

### ISSUE THREAD

**Issue by matheuszabin** [Alecaddd/sequeler#155]
Hi!
In most MySQL browser's isn't mandatory to have a default schema to create a connection.
For example, I've a problem with a ElementaryOS fresh install, because after I've setup a new MySQL server there's no schema to create/save the connection. So I have to use the terminal to create the schema and then access via Sequeler.

**Comment by Alecaddd** [comment]
What do you mean? Can you write a better issue please, highlighting the reasons why you'd like a feature like this, the benefits, what problems it should solve, etc. ?

**Comment by Alecaddd** [comment]
Oh, I see.
Yes, that was an issue I stumbled upon when initially coding Sequeler.
Unfortunately, this is something I can't change as a Database, or Schema, is required by the `LibGDA` in order to create a valid connection.

Yesterday, a new version of the LibGDA was released. I'll see if it allows a direct connection to the HOST without a Database name.

Cheers

**Comment by michaelkanis** [comment]
I'd also like this. Although it is not possible to omit the `DB_NAME` parameter, at least in the CLI of libgda (gda-sql-5.0) you can open a connection using:

`.c myconnection MySQL://username:password@HOST=127.0.0.1;PORT=3306;DB_NAME=`

Note the empty value for `DB_NAME`. That does the same as it would when connecting with the mysql CLI client and not specifying a schema name (i. e. it will tell you `ERROR: No database selected` and you need to `USE someschema`).

Thanks for your work.

**Comment by michaelkanis** [comment]
@Alecaddd Is this kind of pull request wanted? I would also like to tackle other small things, if you give me some feedback. Thanks for your work on Sequler, it's a nice tool.

**Comment by Alecaddd** [comment]
@michaelkanis Just merged, thanks for your contribution. Feel free to log issues or create other PRs to improve Sequeler :+1:
