### ISSUE TITLE
Feature: A bind for "SELECT * FROM table_name"

### ISSUE THREAD

**Issue by matheuszabin** [Alecaddd/sequeler#156]
Hi!
When using softwares like Workbench, always have a shortcut for list all elements in table (of course, with a reasonable LIMIT, to prevent memory issues).
I think could be good a feature like that! Could enhance Sequeler's productivity.
Thank's

**Comment by Alecaddd** [comment]
Once again, please be descriptive and eloquent in creating issues. These simple titles are not helpful at all.
The Content tab already shows all the content of a table, what would this feature be useful for?

**Comment by matheuszabin** [comment]
Sorry, I've seen other "feature issues" here, with no description, so I just follow the other :/ (I'm already added the description to this issue)

**Comment by Alecaddd** [comment]
Thanks for the request.

I don't see the value in having this binding as the Content tab already does that with one single click.
I prefer to not add any predefined bindings for the Query tab as that would mean creating bindings for any Database type.

I prefer to leave the Query tab free of anything and let the user type the SQL commands.

Cheers
