### ISSUE TITLE
The application should open sqlite files

### ISSUE THREAD

**Issue by bilelmoussaoui** [Alecaddd/sequeler#158]
Clicking on a sqlite3 database file should open a new window of Sequeler and either shows a new connection window or directly connect the user to the database if it's already added. 

The mime-type of a sqlite3 database file is `application/vnd.sqlite3`

Steps to handle this (not really that complete, but should give you an idea how to handle this)
- Add the mime type handled by the application to the desktop file 
https://github.com/elementary/code/blob/master/data/io.elementary.code.desktop.in.in#L11
This allows the file manager to show up the app when the user tries to open a file like this. It's also supported by software centers to propose applications that can open a certain mime-type
- `%U` should be after the application's binary file in the `Exec` entry https://github.com/elementary/code/blob/master/data/io.elementary.code.desktop.in.in#L6
- The Application flags should be set to HANDLE_OPEN like with elementary Code https://github.com/elementary/code/blob/master/src/Application.vala#L40
- a `command_line` function should be added to `Application` https://github.com/elementary/code/blob/master/src/Application.vala#L119 it should basically just open the file if it's supported.

**Comment by Alecaddd** [comment]
Oh, that's an interesting and helpful feature, thanks for requesting it.
I will definitely add this sooner or later :smile: 

Right now, the priority for the next version is implementing filtering results in the Content tab with a built-in search based on the table schema.

I will most likely put this feature as a requirement for `v0.7.0`

Cheers

**Comment by bilelmoussaoui** [comment]
I can try to find some time for this next week if you want ;)

**Comment by Alecaddd** [comment]
Absolutely! Fork it and do your magice 😄
I apologize in advanced for my crappy coding.
