### ISSUE TITLE
unable to connect to, not install mysql provider.

### ISSUE THREAD

**Issue by SuPerCxyz** [Alecaddd/sequeler#162]
![screenshot_20181017_073557](https://user-images.githubusercontent.com/17843307/47053473-a6bb3900-d1df-11e8-8a61-c51aa7e59650.png)
![screenshot_20181017_073807](https://user-images.githubusercontent.com/17843307/47053474-a6bb3900-d1df-11e8-9905-0f3024dcbc85.png)

system:fedora 27
Mariadb10.2 has been installed

**Comment by Alecaddd** [comment]
Try installing the mysql provider:
`sudo apt install libgda-5.0-mysql`

Are you running it via the flatpak?

**Comment by SuPerCxyz** [comment]
Fedora does not have libgda-5.0-mysql, and later runs through flatpak.

**Comment by SuPerCxyz** [comment]
But running through flatpak is not very friendly.

**Comment by Alecaddd** [comment]
I'm sorry for the issue, but this is first an elementary os app. I'm not the owner or main maintainer of the flatpak version, but that's the best alternative to running sequeler on another distro.

**Comment by bilelmoussaoui** [comment]
It does work for me here. Please open an issue on the Flathub repository so we can dig in more on how to resolve this issue :)
