### ISSUE TITLE
Can't install it on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by hernanBeiza** [Alecaddd/sequeler#168]
I am trying to install Sequeler using Ubuntu Software App and I am getting this error:

"Cannot perform the following tasks"

![screenshot from 2018-10-31 12-40-17](https://user-images.githubusercontent.com/1325005/47800103-6513ad80-dd0a-11e8-9192-baaa08681790.png)

And when I tried it using SNAP on CLI, I got this:
`
sudo snap install sequeler
`

![screenshot from 2018-10-31 12-45-33](https://user-images.githubusercontent.com/1325005/47800643-7c06cf80-dd0b-11e8-8644-25b224e13599.png)

So finally I installed it using a DEB file, following this instructions (:
https://gist.github.com/b3none/c7764441c91cc69e1543fb6e04acef32

By the way, the app looks as a small beauty! Thanks for your work!

**Comment by Alecaddd** [comment]
I have no idea how in heave is possible that my app is available as a snap in the Ubuntu software center 😅 
From the icon, it looks like that's a really outdated version, v0.4 or something.
The current version is 0.6.3, and you can get it by following the same deb instructions you linked, but by updating the version of the file you're downloading.

Sequeler is also available as a FlatPak if you're not on elementary OS. That package is actively maintained and up to speed with the current version.

Thanks

**Comment by hernanBeiza** [comment]
Thanks for your fast reply! I tried install it using these versions:

![screenshot from 2018-10-31 15-09-00](https://user-images.githubusercontent.com/1325005/47809145-f3922a00-dd1e-11e8-83cf-0c55de94edbb.png)

But doesn't worked :( I had to installed version 0.5.6

**Comment by hernanBeiza** [comment]
Finally I used flatpak. Works like a charm! Thanks!
