### ISSUE TITLE
Pagination: page change hides sliders

### ISSUE THREAD

**Issue by guilmour-asc** [Alecaddd/sequeler#175]
When **changing from a page to another**, in the **Content** view, **the sliders do not appear**, so I have to swap to another main tab (like "Structure" or "Query") and go back to "Content" for the sliders to re-appear.

![peek 26-11-2018 12-14](https://user-images.githubusercontent.com/26415345/49019493-335cfd80-f175-11e8-9080-39672cf36f70.gif)

**Comment by Alecaddd** [comment]
Yup, confirmed. Thanks for the recording.
I will try to push a fix this week.

**Comment by guilmour-asc** [comment]
Thanks for the attention, bud.

**Comment by Alecaddd** [comment]
Could you confirm something?
I noticed that if I have another application open or the GTK inspector, and I change the focus after going to page 2, after a few seconds the scrollbar reappear.
This so weird and inconsistent 😱

**Comment by guilmour-asc** [comment]
Yeah, **confirmed**. Happens to me too.
Maybe it's something with the sliders' mechanism. But it's not a problem to me, anyway.
Great app, you made. Congrats 🎉

**Comment by cjfloss** [comment]
You don't have to change the page, just reloading trigger the problem.

**Comment by Alecaddd** [comment]
Could one of you double check the PR #180 and be sure the issue is fixed?
