### ISSUE TITLE
Move query to a panel not the stack switcher

### ISSUE THREAD

**Issue by Nine-H** [Alecaddd/sequeler#177]
I always remember all table attributes, never make typos, and don't even test my queries, but there's some people out there running phpmyadmin in lxc because they want to use a bunch of windows for reference. I'm glad I'm not one of them but it might be a good idea to accommodate them.

Current behaviour:
query is a view on the stack and clicking it opens it.

Expected behaviour:
clicking query opens up a panel so users can scroll around and carefully copy out important details and check things.

**Comment by Alecaddd** [comment]
Hi, thanks for your suggestion but I'm not gonna implement it.
Moving the Query field to a standalone panel introduces too much overhead in terms of handling multiple views and windows on Query execution.
I'm currently implementing an autocomplete feature that automatically detects the tables and columns names of the currently open database.
That should improve the typing experience of raw queries.
Thanks for using Sequeler
