### ISSUE TITLE
Add a link to the .deb in the ReadMe

### ISSUE THREAD

**Issue by AchilleLacoin** [Alecaddd/sequeler#183]
The installation is just easier on debian-based system with the .deb linked in : http://packages.elementary.io/appcenter/pool/main/c/com.github.alecaddd.sequeler/

Thanks for your work :)

**Comment by bilelmoussaoui** [comment]
That won't work if the use doesn't have the required dependencies on their repos. If a distro want to ship the app, they have to just  add it to their repo. Users can use the flatpak package too which is up to date and fully working.

**Comment by AchilleLacoin** [comment]
Ok, i'll close the issue. The app is usable in ubuntu mate, but the theme is a little off 
![image](https://user-images.githubusercontent.com/36007425/49699526-936e8d80-fbd2-11e8-9d80-6e1d7c3397a2.png)
