### ISSUE TITLE
Use NativeFileChooser

### ISSUE THREAD

**Issue by bilelmoussaoui** [Alecaddd/sequeler#186]
Currently, 
Sequeler uses FileChooser to select a sqlite file. It works great, but in a sandboxed env, this means that we must give `home` access to the application which is not that good...

Gtk added a NativeFileChooser. Which allows you to use a file chooser that would works on both cases without having to give any special access to the Flatpak version. 

As the maintainer of the flatpak version, if you think you don't have the time to work on this. I can take care of it.

**Comment by Alecaddd** [comment]
Thanks for the info.
Feel free to make a PR for it, otherwise, I'll try to take care of this over the weekend.

**Comment by Alecaddd** [comment]
I pushed a fix to the `dev` branch.
I had to replace the `show()` method with the `run()` method as the Open action wasn't triggering the dialog properly.

Would you be able to fetch the branch and give it a spin locally to be sure I didn't break anything?

**Comment by bilelmoussaoui** [comment]
Looks okay to me. Let me check it on a sandboxed env without the home permission and see how it works. (could take a while to build everything on my old laptop)
