### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Alecaddd** [Alecaddd/sequeler#187]
The current icon of Sequeler feels kinda meh, I don't know why but I never fully liked it.

![com github alecaddd sequeler](https://user-images.githubusercontent.com/2527103/49822846-1b6ba900-fd33-11e8-9fcd-42788b981f50.png)

I'm open to suggestions and examples, and I will use this issue to upload tests and collect feedback.

**Comment by harisvsulaiman** [comment]
I like the old icon , please don't change it 😶

**Comment by desiderantes** [comment]
Another inspiration from [icons8](https://icons8.com/icon/11963/data-configuration)

![icons8-database-administrator-100](https://user-images.githubusercontent.com/1703429/49842351-2cdfa000-fd89-11e8-9a81-1e2ac46aa7ad.png)

**Comment by Alecaddd** [comment]
I was thinking about something more like this:
![sequeler-test](https://user-images.githubusercontent.com/2527103/49848159-a1660f00-fd88-11e8-9d34-c9766ce8ccb7.png)

**Comment by JerryCasiano** [comment]
I like the S posted by maxwell108 personally.

But I think it needs to be a little more pronounced, it's a little too subtle.

**Comment by Alecaddd** [comment]
I prefer to avoid using letters in the logo as I don't really like that approach. Also, there are many apps currently using that approach.

I personally prefer to use a stylized version of what the app is for, or if the name allows it, playing with it and using a visual reference tot he object or action.

For Sequeler, I really feel like the database rack or a stack of hard drives is evocative and recognizable, but not too obvious or already seeing.
I also want to have a sort of subtle shout out to Sequel Pro, since the generic UI approach is heavily inspired by that app.

I'm starting to like this one a lot:
![sequeler-test](https://user-images.githubusercontent.com/2527103/49907746-661d1c00-fe2c-11e8-8989-74c5dd86a20a.png)

**Comment by Alecaddd** [comment]
Here's a better resolution since GitHub resizes it a bit and it gets all blurry

![sequeler-test](https://user-images.githubusercontent.com/2527103/49907828-be541e00-fe2c-11e8-9a20-9cfeb44cd3c7.png)

**Comment by Alecaddd** [comment]
Iterating on this idea:
![sequeler-test](https://user-images.githubusercontent.com/2527103/49910174-8ce05000-fe36-11e8-9481-8c15b03c3d4a.png)

**Comment by Alecaddd** [comment]
Another iteration
![sequeler-test](https://user-images.githubusercontent.com/2527103/49980914-5542d800-ff0a-11e8-8e94-45c55cbe84bb.png)
