### ISSUE TITLE
Handle Null queries & databases

### ISSUE THREAD

**Issue by bilelmoussaoui** [Alecaddd/sequeler#200]
See the logs when you run the app from terminal
<pre>** (Sequeler:2): <font color="#6B70C3"><b>CRITICAL</b></font> **: <font color="#258AD1">09:29:47.874</font>: sequeler_services_types_sq_lite_real_show_table_relations: assertion &apos;database != NULL&apos; failed

** (Sequeler:2): <font color="#6B70C3"><b>CRITICAL</b></font> **: <font color="#258AD1">09:29:47.874</font>: sequeler_layouts_views_relations_get_table_relations: assertion &apos;query != NULL&apos; failed

** (Sequeler:2): <font color="#6B70C3"><b>CRITICAL</b></font> **: <font color="#258AD1">09:29:52.044</font>: sequeler_services_types_sq_lite_real_show_table_relations: assertion &apos;database != NULL&apos; failed

** (Sequeler:2): <font color="#6B70C3"><b>CRITICAL</b></font> **: <font color="#258AD1">09:29:52.045</font>: sequeler_layouts_views_relations_get_table_relations: assertion &apos;query != NULL&apos; failed

</pre>
For sqlite service, database could be null. 
https://github.com/Alecaddd/sequeler/blob/085cd17b504b8bcf2027d1c526dac30d7dc91843/src/Services/Types/DataBaseType.vala#L56
Which means on the Interface DatabaseType, it should be handled correctly. Same on the sqlite service.

Same here
https://github.com/Alecaddd/sequeler/blob/085cd17b504b8bcf2027d1c526dac30d7dc91843/src/Layouts/Views/Relations.vala#L142-L144
the query could be null too.

**Comment by Alecaddd** [comment]
Thanks for the report, indeed I completely forgot to handle the possible `null` for an SQLite connection.
I'll patch it for the next release.
