### ISSUE TITLE
meson devel version installed by default on elementary OS

### ISSUE THREAD

**Issue by Alecaddd** [Alecaddd/sequeler#208]
@bilelmoussaoui 
The work that was done to have a `default` and a `Devel` version caused issues on elementary OS.
By default, the app is using the Devel schema, which is blank and caused the app to start empty.

**Comment by Alecaddd** [comment]
I think the problem is here:
https://github.com/Alecaddd/sequeler/blob/master/schemas/meson.build#L2

Shouldn't this be 'development'?

**Comment by bilelmoussaoui** [comment]
Oups:P Sorry for that!
