### ISSUE TITLE
Error when adding a new connection after failed attempt.

### ISSUE THREAD

**Issue by markmorris** [Alecaddd/sequeler#212]
This was a strange one, i tried adding a new connection and input all the correct info other than the password, it failed to connect as it should have, but upon correcting the password it continued to fail to connect. So i saved the connection closed the window and click on the left hand side and it connected first time. So from my understanding of this, it seemed like it cached the password first time around and didn't update it when i change the pass.

**Comment by Alecaddd** [comment]
Uh, interesting.
Were you trying to connect over SSH?
I'll try to recreate the issue and patch it if I find it.
Cheers

**Comment by Alecaddd** [comment]
I fixed this, I'll ship a new version soon.
