### ISSUE TITLE
Error on viewing table with restricted name

### ISSUE THREAD

**Issue by lumnn** [Alecaddd/sequeler#213]
App breaks when user opens a table with a name that's restricted such as "group".

In that case to produce correct SQL it's required to wrap table names in backticks, like:
``SELECT * FROM `group` ``

Opening `group` table results in error:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'group' at line 1

While error can be dismissed, the view ("Structure", "Content", etc.) that was selected while opening table is broken even for other tables. Restart is required to fix that.

**Comment by Alecaddd** [comment]
Thanks for the report.
I will patch it and ship a new version soon.
