### ISSUE TITLE
crashing when view big sqlite table

### ISSUE THREAD

**Issue by CkTD** [Alecaddd/sequeler#215]
I try to view the content of one table in sqlite. The table is large and  about 1.5GB.  I guess it might load all the data to memory... Because it eat all my 12GB ram and then the swap file,  crush my computer finally.
And I also notice that when I  try to view a sqlite database of middle size the application does't response for a long time after i click the content. 
It think it would be faster and use less memory if using limit and offset to just get the content that should be show on one page.

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler and for this bug report.
Indeed, I have to refactor the pagination to properly limit and offset results.
I'll try to patch this and push an updated version later this week.

**Comment by Alecaddd** [comment]
Would you be able to pull PR #245 and check if the issue has been resolved?

**Comment by CkTD** [comment]
I tried to build it. 
Memory issue has been resolved. Consumption remained the same for tables of any size.
But there exist a new bug. Page number can be negative.
![image](https://user-images.githubusercontent.com/30584213/55605761-f7016580-5743-11e9-8f61-d48d28caf6c8.png)
To reproduce:    
Trun to some positive page.  Continuously click on the previous page button quickly.

**Comment by Alecaddd** [comment]
> Memory issue has been resolved

Yay!

> But there exist a new bug. Page number can be negative.

Ah, good find. I need to disable the buttons while a new page is loading the results. Could you open a dedicated bug report for it?

After I fix this I will update the flatpak so you can get it from there without the necessity of building it manually.

**Comment by CkTD** [comment]
Ok . I will open a new issue.
