### ISSUE TITLE
[Feature Request] EXPLAIN support

### ISSUE THREAD

**Issue by gquittet** [Alecaddd/sequeler#218]
Is it possible to support the "EXPLAIN"?
If you need any help, I can help you for the development.

Great job for this tool! :+1:

**Comment by Alecaddd** [comment]
I'll check if `LibGDA` supports that command and implement it.
Thanks for using Taxi 😄

**Comment by gquittet** [comment]
Not Taxi 😁 I'm talking about Sequeler (Postgres, MariaDB, MySQL).

**Comment by Alecaddd** [comment]
Sorry, that was a typo :persevere:

**Comment by gquittet** [comment]
Don't worry, I understood ;)

**Comment by gquittet** [comment]
Great job! :+1:
