### ISSUE TITLE
Dark mode slider doesn't work

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#229]
When I use the slider for Dark and Light modes, nothing happens, even after a restart (although the slider status is preserved over restart).

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by svartrev** [comment]
Screenshot of the problem:
![screenshot-no-dark-mode](https://user-images.githubusercontent.com/8195402/54071961-cfba9400-427c-11e9-91af-45cc82d889e2.png)

**Comment by Alecaddd** [comment]
I'm sorry but I don't support the AUR version, and the Dark Mode is tied to the GTK stylesheet. Try to contact the package maintainer and ask for help.
