### ISSUE TITLE
Saved connections are invisible.

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#230]
When I save a connection, an entry is created in the pane on the left, but the text is invisible, unless a dialog window is open. I've attached two screenshots to explain better:
![screenshot-no-saved-database-names](https://user-images.githubusercontent.com/8195402/54071944-9e41c880-427c-11e9-872c-4fb8c6ceb503.png)
![screenshot-no-saved-database-names-except-when-error-dialog](https://user-images.githubusercontent.com/8195402/54071945-a13cb900-427c-11e9-8a9b-ca12cc0c3b75.png)

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by Alecaddd** [comment]
That seems to be a problem with your GTK theme and that packaged version of Sequeler, which I don't maintain. I'd suggest installing it via FlatPak to guarantee a native and supported experience.
