### ISSUE TITLE
Passwords are not saved

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#231]
When I create a connection, if I enter a password in the dialog, I can connect to the database, but if I save the connection, any attempt to use the saved connection fails, with an access denied error saying "(using password: NO)"

This means that after I've connected, if I change the table from the dropdown, I get the error again, and have to logout, edit a connection, re-enter the password and then connect again.

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by svartrev** [comment]
Possibly connected, when running from the terminal, I get this message when I press the "Connect" button:
`libsecret-Message: 15:22:21.763: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

A brief web search seems to indicate that this might have to do with me not having gnome-keyring installed, so this might be an Arch Linux package missing dependency problem.

That said, you should still handle this gracefully in the application.

**Comment by Alecaddd** [comment]
I don't offer support for packaged versions I didn't do. Currently, on both elementary OS and FlatPak, `libsecret` is required before installing and gets shipped with the application, so this problem doesn't occur. Contact the maintainer of the AUR package or try FlaPak if you're on Arch.
