### ISSUE TITLE
Can't enter correct password after entering wrong password

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#233]
When creating or editing a connection, if you enter an incorrect password and press "Connect", you get an access denied error. If you then enter the correct password, you still get the access denied error. You have to close the dialog and re-create or re-edit the connection to enter the correct password.

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by svartrev** [comment]
Possibly connected, when running from the terminal, I get this message when I press the "Connect" button:
`libsecret-Message: 15:22:21.763: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

A brief web search seems to indicate that this might have to do with me not having gnome-keyring installed, so this might be an Arch Linux package missing dependency problem.

**Comment by Alecaddd** [comment]
Closing because related to #231
