### ISSUE TITLE
Program crashes after entering wrong password and closing dialog twice

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#234]
When editing a connection, if you enter the wrong password and get an access denied error when trying to connect, and then close the dialog, the second time you do this the program crashes without any error message, it just disappears. When running it from the terminal, I get the message "Terminated".

Possibly connected, when running from the terminal, both times when opening the connection dialog, I get this message:
`libsecret-Message: 15:22:21.763: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

This also happens the first time I press the "Connect" button, but not the second time.

A brief web search seems to indicate that this might have to do with me not having gnome-keyring installed, so this might be an Arch Linux package missing dependency problem.

That said, you should still handle this gracefully in the application.

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by Alecaddd** [comment]
Closing because related to #231
