### ISSUE TITLE
Connections list not sortable, or sorted by name

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#236]
The list of connections is not sortable, and isn't sorted by name. It seems to be sorted by last saved date, as any entry I edit and save jumps to the top of the list. Another minor point, but in terms of UI design, this makes the list less predictable, and therefore harder to use. Allowing a custom sort order would be nicest, but failing that, sorting by something like name is probably better.

**Comment by Alecaddd** [comment]
That's a good point.
I'll investigate and start working on a manual reordering of saved connections.
Thanks
