### ISSUE TITLE
Authentication by public key fails

### ISSUE THREAD

**Issue by pmk1c** [Alecaddd/sequeler#237]
I'm using the Flatpak version of Sequeler and I'm trying to connect to a DB via SSH Tunnel. Unfortunately the connection fails with the following messge: "Authentication by public key fails".

Trying to connect via `ssh USERNAME@IP` in the Terminal works. Is it possible there's some problem accessing the public key?

**Comment by Alecaddd** [comment]
Please, open this issue in the Flatpak dedicated repository as I'm not the maintainer of that port.
https://github.com/flathub/com.github.alecaddd.sequeler
