### ISSUE TITLE
Match dialog button ordering to HIG

### ISSUE THREAD

**Issue by danrabbit** [Alecaddd/sequeler#24]
Dialogs should place their cancel/close button directly before the affirmative action button, with alternative actions coming before the cancel/close button. Incidental actions (ones that aren't choices that close the dialog) should be separately aligned to the beginning of the dialog instead of at the end with the other buttons. See this HIG entry: https://elementary.io/docs/human-interface-guidelines#button-order

That means for the new connection dialog the order should probably be:

`[Test Connection]       [Save Connection] [    Cancel    ] [    Connect    ]`

**Comment by Alecaddd** [comment]
Thank you so much for this, I will implement the changes in the next version!

**Comment by Alecaddd** [comment]
Update UI to follow the HIG specs.
Will publish in the next release.

![dialog-buttons](https://user-images.githubusercontent.com/2527103/31314260-5a37a960-abb1-11e7-8230-0a273b54f1e8.png)
