### ISSUE TITLE
0.6.8 fails to build on aarch64 and armvl7

### ISSUE THREAD

**Issue by TeddyDD** [Alecaddd/sequeler#242]
Build fails on those two architectures. It appears that some definitions in libfixposix.vapi are duplicated but I can't quite figure out what's wrong.

Build logs:
https://travis-ci.org/void-linux/void-packages/jobs/510049749
https://travis-ci.org/void-linux/void-packages/jobs/510049750

version: 0.6.8
vala: 0.42.6
libfixposix: 0.4.3

**Comment by Alecaddd** [comment]
Mh, that's weird.
I'm not sure if it could be related to this old PR: https://github.com/Alecaddd/sequeler/pull/206

**Comment by TeddyDD** [comment]
yeah its seems that removing [this](https://github.com/Alecaddd/sequeler/blob/7461f43aeffa91c9ed9cb21e967145fbb0f68bbe/src/meson.build#L66) line fixes problem for aarch64, haven't check armvl7 yet

**Comment by Alecaddd** [comment]
Keep the `vala_args` but remove the ` + ['--pkg', 'libfixposix']` part

**Comment by TeddyDD** [comment]
[This patch](https://github.com/void-linux/void-packages/blob/6c70bf9dc1356a4b65e2c2caf7ef3566896c2f9a/srcpkgs/sequeler/patches/aarch64-armv7l.patch) fixed builds on my machine, but fails on travis.  Weird.

**Comment by Alecaddd** [comment]
@TeddyDD this issue is appearing also on the FlatPak build for Arch.
Can you try to remove the `dependency('libfixposix')` and add ` + ['--pkg', 'posix']` after the `vala_args`?

**Comment by TeddyDD** [comment]
not sure if it's necessary since 0.6.9 builds fine without any patches 
https://travis-ci.org/void-linux/void-packages/builds/515694629?utm_source=github_status&utm_medium=notification
