### ISSUE TITLE
Hard-coded Elementary theme renders app unusable

### ISSUE THREAD

**Issue by ripefig** [Alecaddd/sequeler#249]
![image](https://user-images.githubusercontent.com/45201036/56074380-f73fd780-5db9-11e9-9a3a-ef6142e2b4a9.png)

This is how the app looks on KDE.
Just a heads up. By hard coding a non-standard GTK theme, Elementary apps look either totally broken or horribly out of place on other desktops. This may be a feature from the perspective of Elementary designers, but it is really horrible for the applications. I don't know how strong the theme lock-in is and whether there is much that can be done short of abandoning the platform entirely. 

Why bother putting the apps on flathub if they aren't going to run properly outside elementary OS? Makes more sense to have a separate flatpak repo so users of more common desktops don't accidentally install incompatible apps.

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
Please, report this issue to the dedicated flathub repo where you will get some help from the maintainers: https://github.com/flathub/com.github.alecaddd.sequeler

Regarding your criticism
>Why bother putting the apps on flathub if they aren't going to run properly outside elementary OS?

Sequeler is first and foremost an elementary app that I decided to create for that distro, following that specific HIG and stylesheet. Shipping the flatpak with the elementary theme is a recommended behaviour to ensure visual consistency and fidelity with the original app.
Without that, I would have hundreds of bug reports related to missing/wrong icons, weird colors, strange borders, etc.

I'm sure the issue you're experiencing with KDE is fixable through flatpak as the app is successfully used on solus, fedora, and other distributions.

Closing this as it's not an issue related to Sequeler itself.
