### ISSUE TITLE
[Question] Connection to SQLite

### ISSUE THREAD

**Issue by artemanufrij** [Alecaddd/sequeler#25]
How to connect to SQLite? I tried to input path into `host` but its not possible to test connection if user name and password are empty. 

Maybe it would be useful to choose database type as first and then host url or file. 
Additionally: SQLite hasn't Database Name and it would be useful to have an option like `no username/passwort necessary`.

**Comment by Alecaddd** [comment]
Yes, good call.
Thanks for your feedback, I'll be sure to implement it for the next release!

**Comment by Alecaddd** [comment]
What about this solution?
The modal updates if you select SQLite and the connection is allowed by specifying only the directory and the file name.

![sqlite-dialog](https://user-images.githubusercontent.com/2527103/31326868-de495de2-ac7f-11e7-999c-804a11511ad0.png)

**Comment by artemanufrij** [comment]
@Alecaddd that's looks good!

PS: SQLite path is broken after editing existing connection. It looks like this:
`%252fhome%252fartem%252f.cache%252fcom.github.artemanufrij.playmymusic%252fdatabase.db`

**Comment by Alecaddd** [comment]
@artemanufrij that's the encrypted version of the path necessary to be used in the GDA Connection library, but it shouldn't return to you when you edit a connection.
Will investigate, thanks for the update.

**Comment by Alecaddd** [comment]
I found and fixed the issue.
It turned out I was encrypting twice the data when initializing a connection directly from within the open dialog. The issue wasn't happening while connecting from the library without opening the dialog.

I rewrote that section and the issue have been solved.
Pushing a new version to the AppCenter this evening.

**Comment by artemanufrij** [comment]
@Alecaddd thank you very much
