### ISSUE TITLE
Connect to SSH 

### ISSUE THREAD

**Issue by Kutuzovska** [Alecaddd/sequeler#251]
Sorry, but i don't understand what is the problem:)

ssh root@[host] -p 8899     ->     is working.
ssh key                                ->    ~/.ssh/id_rsa

on Sequeler:
Host: [host]
Username: root
Password: null/root/[password]
port: 8899

![Снимок экрана от 2019-04-19 19 42 36](https://user-images.githubusercontent.com/34393267/56433943-58483d80-62db-11e9-9c38-ae5d2ab5321d.png)

**Comment by Alecaddd** [comment]
Are you using the flatpak version or are you on elementary os?
From the terminal, it seems like your SSH password is not properly stored and retrieved from libsecret.

**Comment by Kutuzovska** [comment]
> Are you using the flatpak version or are you on elementary os?
> From the terminal, it seems like your SSH password is not properly stored and retrieved from libsecret.

Elementary. 
did a check ssh_key  of root   path: /root/.ssh/id_rsa -> not working

Terminus - client for ssh -> working
Connect of terminal        -> working
Sequeler                         -> no :(

**Comment by Alecaddd** [comment]
Does your SSH connection require a password?
What does this mean? `Password: null/root/[password]`

**Comment by Kutuzovska** [comment]
@Alecaddd 
I connect to server without password. But, server has connection by password , it's password "root" or "[password]".

**Comment by Alecaddd** [comment]
If your SSH connection doesn't require a password, you shouldn't write anything in your SSH password field. Server password and SSH password are two different things.
Also, your SSH public key should be stored in your user's directory `~/.ssh/id_rsa`, not in the `root/`, unless your account user is root.

**Comment by berliner** [comment]
I am also having issues. Basically, SSH tunneling doesn't work for me, while I can ssh into the server from the terminal without any problems.
SSH public and private keys are in `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub`
I have installed sequeler from the elementary app store (v0.7.0).

**Comment by jameron** [comment]
I am having trouble connecting to AWS RDS via an SSH tunnel that requires a .pem key and no password. Is this supported?

**Comment by mlopezgva** [comment]
Hello. Is there a config file where I can change the default name of the key file from `is_rsa` (which I don't have nor have any reason to) to anything else? Or can I set up the tunnel before connecting to the remote server and use it "directly"?

Thanks.

**Comment by jameron** [comment]
thx, do you know where is the file typically on linux system?

**Comment by Alecaddd** [comment]
Is this issue still present with the latest version of Sequeler?
You can also select a custom public key instead of being forced to use the id_rsa from the default location.

**Comment by jameron** [comment]
Unfortunately, I am unable to check as my Fedora machine went down and I am now using a Mac exclusively.
