### ISSUE TITLE
Saving a new connection deletes old ones

### ISSUE THREAD

**Issue by michelesolytic** [Alecaddd/sequeler#255]
While using Sequeler (version 0.7.0-2.fc29 on Fedora 29) it seems not possible to add a new connection, as doing so deletes the previously saved ones.
To reproduce, just install Sequeler from the official fedora repo (0.7.0-2.fc29) add a new connection, close sequeler, restart it, try to add another one.

**Comment by Alecaddd** [comment]
Uh, that's really odd, I never experienced this issue, and its the first time I'm getting this report.
Did you install it via Flatpak?

**Comment by michelesolytic** [comment]
Thanks for the answer!
No, I am using the Fedora repository version (as it keeps the same Gnome feedback of the rest of the system, the flatpak one looks really elementaryOS oriented).

**Comment by Alecaddd** [comment]
You should reach out to the maintainers of the Fedora repo and check with him. This issue doesn't appear on elementary OS nor with the Flatpak.
