### ISSUE TITLE
Can't connect to MySQL

### ISSUE THREAD

**Issue by CJ-Martinez** [Alecaddd/sequeler#26]
Upon testing or connecting to a mysql database, the app is showing the message below

**No provider 'MySQL' installed**

Is there a prerequisite package that needs to be installed?
btw, I am trying to connect to a remote server.

**Comment by WilsenHernandez** [comment]
I'm running into the same problem connecting to a local database

**Comment by wout** [comment]
Me too. Tried this with both local as well as remote connections. Always get this **No provider 'MySQL' installed**. It seems like a great app but currently it's unusable.

**Comment by Alecaddd** [comment]
Oh damn, so sorry everyone! I completely forgot to add a couple of libraries to the Deb, fixing it right now.
You should install the missing `libgda-mysql` and it should work.
I'm the worst 😫

**Comment by WilsenHernandez** [comment]
I installed `libgda-5.0-mysql` from the Ubuntu repositories and it worked.
Waiting for an update soon then. Great work man

**Comment by MaizerGomes** [comment]
Same with postgres. Had to install libgda-5.0-postgres

**Comment by Alecaddd** [comment]
Included the missing libraries in the new build.
Pushing a new version to the AppCenter later this evening

**Comment by jdenson** [comment]
After updating to 0.2.1 today, I was still receiving this error. However, manually installing `libgda-5.0-mysql` as others suggested seems to have resolved the issue.

**Comment by Alecaddd** [comment]
Ouch, so sorry.
I'm starting to think it's an issue with the packages that I can't fix.

So, in the debian control file I added these packages
```
libgda-5.0-dev,
libmysqlclient-dev,
libpq-dev,
libgda-5.0-mysql,
libgda-5.0-postgres
```

All good in compiling. 

The problem, is the list of dependencies in the **CMakeList.txt**
In order to properly compile everything, I need to specify the name of those packages in this format.
```
libgda-mysql-5.0
libgda-postgres-5.0
```
Because if I write the as they're supposed to be, like `libgda-5.0-mysql`, I get an error that the package was not found, even if I have installed on my machine.

This is messed up >_>

**Comment by ivanaugustobd** [comment]
Already installed `libgda-mysql` like suggested, but the error keep occurring..

Fedora 27
Sequeler 0.4.3 from "updates" repo
libgda 5.2.2
MySQL both 8.0.3 and 5.5.59 [from Docker](https://store.docker.com/community/images/mysql/mysql-server)

Have I missed something? :thinking:

**Comment by Alecaddd** [comment]
I don't release or maintain the Fedora repo, not sure who does that.
I'd suggest compiling from source the recent release of Sequeler, which is v.0.5.4
Cheers

**Comment by ivanaugustobd** [comment]
I've tried to install the packages listed on README.md (gtk+ granite glib gee gobject libxml libgda gtksourceview), but `gee`, `gobject` and `gtksourceview` can't be found (probably due a package name mismatch between deb and rpm systems) :/

Even so I tried to compile it, but get these messages after `cmake -DCMAKE_INSTALL_PREFIX=/usr ../`:
```
-- Checking for modules 'gtk+-3.0;granite;glib-2.0;gee-0.8;gobject-2.0;libxml-2.0;libgda-5.0;libgda-mysql-5.0;libgda-postgres-5.0;gtksourceview-3.0'
--   Package 'gtk+-3.0', required by 'virtual:world', not found
--   Package 'granite', required by 'virtual:world', not found
--   Package 'glib-2.0', required by 'virtual:world', not found
--   Package 'gee-0.8', required by 'virtual:world', not found
--   Package 'gobject-2.0', required by 'virtual:world', not found
--   Package 'libxml-2.0', required by 'virtual:world', not found
--   Package 'libgda-5.0', required by 'virtual:world', not found
--   Package 'libgda-mysql-5.0', required by 'virtual:world', not found
--   Package 'libgda-postgres-5.0', required by 'virtual:world', not found
--   Package 'gtksourceview-3.0', required by 'virtual:world', not found
```
Even the installed packages, like `gtk3` accuses "not found" while building..

I'll try with some different ways later and post here if I've can get some kinda of solution for this ;)

**Comment by Mystro256** [comment]
@ivanaugustobd Installing the flatpak via flathub did the trick for me.

Also, I made a bug report for the Fedora package:
https://bugzilla.redhat.com/show_bug.cgi?id=1580061

**Comment by decathorpe** [comment]
@Alecaddd I maintain the fedora package. Sorry about the noise, fedora users should report bugs with downstream first.

@ivanaugustobd @Mystro256 the libgda package in fedora is broken and / or outdated since fedora 24, which is why MySQL support isn't present/working. (I can't fix that myself and the libgda maintainer seems to be AWOL).

Since the flatpak version seems to work according to the comments above, I suggest using that until the libgda package is fixed on fedora.

**Comment by Alecaddd** [comment]
@decathorpe no worries, and thank you so much for checking the issues related to Fedora.

The LibGDA is a real pain, but it's so handy for its bindings and methods to access multiple DBs.

I'm looking into dropping that library and use directly specific libraries for each DB type, which should be somewhat updated and maintained.

Cheers

**Comment by fabriscorol** [comment]
> @ivanaugustobd Installing the flatpak via flathub did the trick for me.
> 
> Also, I made a bug report for the Fedora package: https://bugzilla.redhat.com/show_bug.cgi?id=1580061

Hi @Mystro256
I installed the version from the flatpak from Flathub and unfortunately I have the same error "No provider 'MySQL' installed"

OS Fedora 36

**Comment by mickeymond** [comment]
Any positive feedback from the Fedora RPM side of things?
I am using Fedora 37 Workstation....

**Comment by mochaaP** [comment]
@decathorpe Please considering downgrade the weak deps to the `libgda5-*` package family, as we have 6.0 on the `libgda-*` ones. :beers:
