### ISSUE TITLE
Mariadb Connection Bug

### ISSUE THREAD

**Issue by arganaphangquestian** [Alecaddd/sequeler#261]
![2019-06-13-191000_608x541_scrot](https://user-images.githubusercontent.com/44634632/59431506-497b9400-8e0f-11e9-9c02-e6c6b47292e5.png)

i choose MariaDB Connection, but when i click test connection, app showing ``No Provider "MySQL" Installed``

**Comment by Alecaddd** [comment]
Which distro are you using?
Did you install Sequeler via flatpak or something else?

**Comment by arganaphangquestian** [comment]
I use manjaro os.
Is it available for arch based?
I follow you instructions on Readme.md for installation proccess

**Comment by cjfloss** [comment]
@arganaphangquestian Do yo have `libgda-mysql` installed?
if not, just install it.
`sudo pacman -S libgda-mysql`

**Comment by Alecaddd** [comment]
I know many users are using it successfully on Arch.
I'd suggest installing it via flatpak as you'll get proper updates and support from flathub maintainers.
Regarding your issue , @cjfloss might be right thinking you're probably missing the mysql provider.
