### ISSUE TITLE
UX: Click on the saved connection name to open it

### ISSUE THREAD

**Issue by batisteo** [Alecaddd/sequeler#263]
Now, in order to connect to a saved database, one have to click on the three-dot menu, which is actually visible only on hover, and then click the first item on it.

I would remove this item from the menu, and just allow to click on the button to connect.
The Edit and Delete options could stay on the menu.
What do we think?

**Comment by Alecaddd** [comment]
That's not necessary as you can double click on the database name itself to open the connection.
