### ISSUE TITLE
Row count labels are very hard to see in dark mode

### ISSUE THREAD

**Issue by flyingpimonster** [Alecaddd/sequeler#267]
Example: 
![Screenshot from 2019-07-02 23-57-59](https://user-images.githubusercontent.com/24497353/60564448-49dbc080-9d25-11e9-806c-7f7e77c47479.png)

**Comment by Alecaddd** [comment]
Which OS and theme are you using?
I can't recreate this issue on elementary OS, and the FlatPak app should install the elementary stylesheet to avoid these type of issues.

**Comment by flyingpimonster** [comment]
I'm using the flatpak on Fedora 30. The Elementary stylesheet loads just fine. My system theme is Adwaita Dark.

**Comment by Alecaddd** [comment]
Thanks for the info.
This seems an issue related to the flatpak, could you please open this issue in this repo so the maintainer can take care of it? https://github.com/flathub/com.github.alecaddd.sequeler
