### ISSUE TITLE
Update version on flathub

### ISSUE THREAD

**Issue by kilbiller** [Alecaddd/sequeler#272]
Hi,

I wanted to use sequeler on ubuntu but I have a bug with a postgres database that seems to fixed on 7.2.
The latest version on flathub is 7.0.
I tried to build it from source but I couldn't build the dependencies on ubuntu.

Can you update the package to the latest version ?
Thank you.

**Comment by Alecaddd** [comment]
I'm not the maintainer of the flathub repo. You should write to them

**Comment by otsaloma** [comment]
https://github.com/flathub/com.github.alecaddd.sequeler/pull/19

**Comment by bilelmoussaoui** [comment]
The package is up to date now!
