### ISSUE TITLE
Bug with multiple lines in queries

### ISSUE THREAD

**Issue by wout** [Alecaddd/sequeler#273]
When I write a query on multiple lines, only the first line seems to be executed.

**Multiple lines**:

![image](https://user-images.githubusercontent.com/107324/63214817-9a647d00-c11d-11e9-8599-da42118edd4d.png)

**Single line**:

![image](https://user-images.githubusercontent.com/107324/63214831-bbc56900-c11d-11e9-8283-1647f21f3d40.png)

**Comment by Alecaddd** [comment]
Thanks for the report.
I'll fix this for the next release.
