### ISSUE TITLE
ctrl-enter with multiple queries does not work

### ISSUE THREAD

**Issue by mispp** [Alecaddd/sequeler#274]
e.g. hitting ctrl-enter while cursor is on the 2nd query fails with "syntax error at or near select" pointing line 3.

```
select * from information_schema.views

select * from information_schema.tables
```

**Comment by Alecaddd** [comment]
That's because your syntax is wrong.
Each SQL query should end with a ;
Sequeler will execute the one where your cursor is.

**Comment by mispp** [comment]
ahh, thanks for clarifying, didnt think that ";" should be the one causing issue.
would you consider changing the behavior that queries work even without ";"?

there is one issue though - when cursor is on the beginning of the line, ctrl-enter doesnt work.
