### ISSUE TITLE
tabs for different queries / files

### ISSUE THREAD

**Issue by mispp** [Alecaddd/sequeler#276]
adding tabs for different files containing sql queries would be much more useful than only one query button per connection

**Comment by Alecaddd** [comment]
Can you be a bit more clear?
Do you mean having the ability to have a notebook query tab with multiple results tabs for the same connection, or multiple tabs with different connections in the same windows?

**Comment by mispp** [comment]
sure.

one tab would have one result set, that would be replaced whenever you run a query in that tab. like it works now, only instead of one text editor and one data grid, you'd have as many as you like, each set in its own tab.

in one application window, you can have multiple connections (e.g. one to mysql, the other to postgres, etc). each tab can use any established connection and send queries to it and receive results. you can pick in the tab which connection you want to use (so it is not fixed).

something like
![img](https://i.ytimg.com/vi/P1WKOQnntVg/maxresdefault.jpg)

**Comment by Alecaddd** [comment]
Yes, this feature is next in the release cycle. After I publish the current version which introduces a bunch of fixes and improvements, adding a notebook widget to handle multiple query tab is next in the list.

**Comment by Alecaddd** [comment]
I started working on this feature in PR #314 
The first release will have just a simple notebook with up to 1 restoreable tab.
In future PRs I will implement the saving of the latest opened tabs, alongside the queries written in it.
