### ISSUE TITLE
switch to dark mode crashes app

### ISSUE THREAD

**Issue by Cyborgscode** [Alecaddd/sequeler#280]
OS: Fedora 29 ( up2date on 17.9.2019)
Desktop: Cinnamon
Name         : sequeler
Version      : 0.7.3
Release      : 1.fc29
Architecture : x86_64
After testing some festures, i switched to dark mode and the app crashed hard with:

(Sequeler:20428): Gtk-WARNING **: 11:55:03.370: Attempting to sort on
invalid type GdaTimestamp
**
Gtk:ERROR:gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code
should not be reached
Abgebrochen (Speicherabzug geschrieben)
{ Interrupted (Coredump written) }

**Comment by Alecaddd** [comment]
I guess you're using via Flatpak.
This doesn't happen on elementaryOS, sorry. Please, open an issue on the flathub repo as I'm not the maintainer of that fork.
https://github.com/flathub/com.github.alecaddd.sequeler
