### ISSUE TITLE
Improvements: "jump to" & "errormessage box"

### ISSUE THREAD

**Issue by Cyborgscode** [Alecaddd/sequeler#281]
- a table with > 300k  entries sum up to 347 pages, when content is
shown. There is no fast way to get to the last page
and the sort order for table cols isn't working yet.

- if a custom query is syntactically invalid, a requester appears. This
is IMHO a massive interruption of the workflow.
A error message box between the query box and the results, which is only
visible in an error case. This would be a far better solution.

**Comment by Alecaddd** [comment]
The `Jump to` feature just landed on master and it's on the queue to be release on elementary OS.
I'm now working on removing the Error dialog in favour of an inline message.
