### ISSUE TITLE
Crashes when trying to save, test or connect to a  Postgres connection

### ISSUE THREAD

**Issue by mikerussellnz** [Alecaddd/sequeler#287]
As soon as click test, save or connect and PostgreSQL is selected as db type, app crashes with this error.  This is happening on Fedora 31. 

free(): invalid pointer
Aborted (core dumped)

Backtrace:
gdb) bt
#0  0x00007ffff6e73625 in raise () at /lib64/libc.so.6
#1  0x00007ffff6e5c8d9 in abort () at /lib64/libc.so.6
#2  0x00007ffff6eb74af in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff6ebea6c in annobin_top_check.start () at /lib64/libc.so.6
#4  0x00007ffff6ec044c in _int_free () at /lib64/libc.so.6
#5  0x00007ffff74843cd in g_free () at /lib64/libglib-2.0.so.0
#6  0x000055555558a160 in sequeler_widgets_connection_dialog_package_data ()
#7  0x000055555558bfec in _sequeler_widgets_connection_dialog_on_response_gtk_dialog_response ()
#8  0x00007ffff756ac62 in g_cclosure_marshal_VOID__BOOLEANv () at /lib64/libgobject-2.0.so.0
#9  0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff7585228 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#12 0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff7585228 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#14 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#15 0x00007ffff79cf56e in gtk_button_do_release () at /lib64/libgtk-3.so.0
#16 0x00007ffff79cf5d8 in gtk_real_button_released () at /lib64/libgtk-3.so.0
#17 0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#18 0x00007ffff7585228 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#20 0x00007ffff79cda04 in multipress_released_cb () at /lib64/libgtk-3.so.0
#21 0x00007ffff7c7e211 in _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv () at /lib64/libgtk-3.so.0
#22 0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#23 0x00007ffff7585228 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#24 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#25 0x00007ffff7a962ec in gtk_gesture_multi_press_end () at /lib64/libgtk-3.so.0
#26 0x00007ffff756bb96 in g_cclosure_marshal_VOID__BOXEDv () at /lib64/libgobject-2.0.so.0
#27 0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#28 0x00007ffff7585228 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#29 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#30 0x00007ffff7a93352 in _gtk_gesture_check_recognized () at /lib64/libgtk-3.so.0
#31 0x00007ffff7a94983 in gtk_gesture_handle_event () at /lib64/libgtk-3.so.0
#32 0x00007ffff7a97956 in gtk_gesture_single_handle_event () at /lib64/libgtk-3.so.0
#33 0x00007ffff7a5ef20 in gtk_event_controller_handle_event () at /lib64/libgtk-3.so.0
#34 0x00007ffff7c20d5d in _gtk_widget_run_controllers () at /lib64/libgtk-3.so.0
#35 0x00007ffff7c77d1f in _gtk_marshal_BOOLEAN__BOXEDv () at /lib64/libgtk-3.so.0
#36 0x00007ffff7568996 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#37 0x00007ffff7584e6a in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#38 0x00007ffff75859d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#39 0x00007ffff7c22793 in gtk_widget_event_internal () at /lib64/libgtk-3.so.0
#40 0x00007ffff7ade1d8 in propagate_event () at /lib64/libgtk-3.so.0
#41 0x00007ffff7ae03eb in gtk_main_do_event () at /lib64/libgtk-3.so.0
#42 0x00007ffff77c8f79 in _gdk_event_emit () at /lib64/libgdk-3.so.0
#43 0x00007ffff7827666 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#44 0x00007ffff747e4a0 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#45 0x00007ffff747e830 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#46 0x00007ffff747e8d3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#47 0x00007ffff7690c75 in g_application_run () at /lib64/libgio-2.0.so.0
#48 0x000055555556319d in _vala_main ()
#49 0x00007ffff6e5e1a3 in __libc_start_main () at /lib64/libc.so.6
#50 0x000055555556308e in _start ()

**Comment by Alecaddd** [comment]
I guess you're using via Flatpak.
This doesn't happen on elementaryOS, sorry. Please, open an issue on the flathub repo as I'm not the maintainer of that fork.
https://github.com/flathub/com.github.alecaddd.sequeler
