### ISSUE TITLE
AWESOME WORK - Suggestion

### ISSUE THREAD

**Issue by leonbollerup** [Alecaddd/sequeler#289]
Hi there,

Awesome work - i asume you are using https://www.sequelpro.com/ as a inspiration.

As a recent migrate from macOS to ChromeOS (with crostini) i love what you are doing here - is there any plans to add support for editing without writing complicated SQL queries?

**Comment by Alecaddd** [comment]
Yup, this type of implementation is on its way.
Duplicate of Bug #260
