### ISSUE TITLE
Favorites labels unreadable in light mode

### ISSUE THREAD

**Issue by berliner** [Alecaddd/sequeler#291]
On Solus 4.0 with Budgie using a light theme, the favorites list seems to use a white font on gray background which makes it close to impossible to read the labels. The only option to work around that for the moment seems to be switching to dark mode in Sequeler.
![sequeler-issue-font-color](https://user-images.githubusercontent.com/205433/69053122-000c2200-0a09-11ea-9db6-b458efa0c480.png)

Not sure what else you need to know.

**Comment by Alecaddd** [comment]
I guess you're using it via Flatpak.
This doesn't happen on elementaryOS, sorry. Please, open an issue on the flathub repo as I'm not the maintainer of that fork.
https://github.com/flathub/com.github.alecaddd.sequeler

**Comment by berliner** [comment]
Not a flatpack but from here: https://dev.getsol.us/source/sequeler/
I have filed an issue with the solus team (https://dev.getsol.us/T8494) and the theme maintainers (https://gitlab.com/tista500/plata-theme/issues/86).

**Comment by berliner** [comment]
Actually, this also happens in elementary when not using the default elementary theme, but Adwaita (the only other one I tested it with on elementary).

![Screenshot von 2019-11-18 22 09 54](https://user-images.githubusercontent.com/205433/69094432-a0396980-0a50-11ea-8e1b-b051d2b00da1.png)
![Screenshot von 2019-11-18 22 14 40](https://user-images.githubusercontent.com/205433/69094545-dd056080-0a50-11ea-8af4-239733658086.png)

In the first image, the sequeler app does not have the focus and the favorite labels display correctly. However in the second image, where sequeler has the focus, the labels are barely readable.

Therefor I reopen the ticket, hoping this is something that could be fixed here instead of for each single theme.

**Comment by FranciscoDA** [comment]
For what it's worth, I fixed this by removing some style properties.
```sh
$ git diff
diff --git a/data/stylesheet.css b/data/stylesheet.css
index 6279751..6391271 100644
--- a/data/stylesheet.css
+++ b/data/stylesheet.css
@@ -2,22 +2,9 @@
     font-weight: 600;
 }
 
-.library-box {
-    background-color: transparent;
-}
-
-.library-box:selected .library-btn {
-       background-color: transparent;
-}
-
-.library-box:selected .library-btn image {
-       color: @fg_color;
-}
-
 .library-inner-box {
     background: transparent;
     transition: background 320ms ease;
-    color: @fg_color;
 }
 
 .library-inner-box .library-btn {
```

It seems that setting the background-color to transparent defaults fg_color to white
