### ISSUE TITLE
Allowing to enter page number in pagination

### ISSUE THREAD

**Issue by wout** [Alecaddd/sequeler#292]
Not unrelated to #282, it would be great to be able to jump to a page:

![image](https://user-images.githubusercontent.com/107324/69903880-3fd2f200-1397-11ea-9472-01bbd216efbf.png)

Now, sorting only occurs in the current page. Having the possibility to jump to a certain page would help very much.

**Comment by Alecaddd** [comment]
A quick heads up to let you know that I implemented a quick pagination popover and it will be available in the next release of Sequeler.
![Screenshot from 2020-04-04 16-45-11](https://user-images.githubusercontent.com/2527103/78463617-c8d69e80-7693-11ea-8a4e-71d0ec23d87a.png)
