### ISSUE TITLE
Problem with "caching_sha2_password"

### ISSUE THREAD

**Issue by stefano-b** [Alecaddd/sequeler#294]
I'm experiencing an issue when I try to connect to a database or even when testing the connection. Here is the error message:

`Plugin caching_sha2_password could not be loaded: /usr//usr/lib64/mysql/plugin//caching_sha2_password.so: cannot open shared object file: No such file or directory`

Some points that I think should be considered:
- I'm using openSUSE Tumbleweed, and sequeler was installed from the repository (no flatpak version)
- I'm using a LAMP stack from [Bitnami](https://bitnami.com/stack/lamp), which is essentially a self-contained standalone installation (mainly because I didn't want to install and manage all server components separately from my distro's repository).
- Judging from the error message, the path that sequeler is checking does not seem to be correct (it has a couple of double slashes `//` where there should be only one and `/usr` is repeated two times).

My setup is probably a bit different from what you use, I'm not sure if the problem can be solved from you, but I thought to report this nonetheless.

**Comment by Alecaddd** [comment]
This seems more an OpenSuse issue than a Sequeler one as Sequeler uses the `libsecret` library to handle encrypted password.

**Comment by nodgear** [comment]
Issue still happens on ElementaryOS version (AppStore)
