### ISSUE TITLE
Cannot connect to hosts that are accessible via SSH through netcat proxies

### ISSUE THREAD

**Issue by codemedic** [Alecaddd/sequeler#297]
I have a few MySQL / MariaDB servers that are not accessible directly. They have to be reached via a "jump host". Also the user allowed to connect to the server is allowed to connect only from localhost.

My SSH config is already setup to jump through which ever jump hosts, so I would expect sequeler to follow those as well. Would that not be possible?

**Comment by Alecaddd** [comment]
Sequeler currently can't read your SSH config.
You need to set up the SSH tunnel manually in the Connection Dialog.
![Screenshot from 2020-02-07 08-58-35](https://user-images.githubusercontent.com/2527103/74049022-239b9480-4988-11ea-964d-5564b64fe830.png)
