### ISSUE TITLE
Allow export to CSV

### ISSUE THREAD

**Issue by AlonsoEnrique** [Alecaddd/sequeler#30]
This format is very useful for reports and more

**Comment by Alecaddd** [comment]
That's a feature already written in the roadmap, together with the ability to export an sql dump.
Cheers

**Comment by Alecaddd** [comment]
The roadmap is in the Projects tab of this very own repo.
I just started working on this feature to export data in CSV, SQL, and Plain TXT.

No import of Database for now. There are future plans of implementing SQL import, but it's not a priority before version 1.
Cheers

**Comment by mpmont** [comment]
Will this also allow to import data into a table via csv?

**Comment by Alecaddd** [comment]
@mpmont no, that's not allowed yet. It's a feature will come later
