### ISSUE TITLE
SQL Field doesn't clear upon successful execution.

### ISSUE THREAD

**Issue by MerlinElMago** [Alecaddd/sequeler#302]
Hello,
executing several SQL statements from within Sequeler is kind of tedious due to the fact that the statement stays in the textfield and has to be deleted in order to write a new one. It may be a feature and not a bug, but it makes working with lots of statements very strenous.The solution in my opinion is to either provide a checkbox next to the "Execute SQL" button to enable this functionality, or enable a separate shortcut to execute cleaning the text.

Best Regards
Merlin

**Comment by Alecaddd** [comment]
This seems like an extra feature that doesn't bring any improvement other than adding another button to the interface.
- Clearing the text after a successful run is very wrong as you can't assume the user won't need that query for later.
- You can run multiple queries one after another by writing them all separated by a semicolon `;` and highlight the query you want to run.
- You can easily clear the area by selecting the text with <kbd>CTRL</kbd>+<kbd>a</kbd> and <kbd>Delete</kbd>
