### ISSUE TITLE
Saved connections aren't quite working

### ISSUE THREAD

**Issue by StuTheBearded** [Alecaddd/sequeler#329]
If I save a connection then try to connect it fails with the error message "access denied for user 'root'@'192.168.0.100' (using password: NO). It looks like the password isn't saving an I don't get a prompt for it either.

Create a new connection
Give the connection a name
Select MySQL
Enter the IP address
Enter a username
Enter the password
Click "Test Connection"
Click "Save Connection"
Click "Close"
Double click the new connection, and error appears.

Edit the connection and it takes a while to populate the boxes (at least 30 seconds), password is missing.

But wait there's more. If I haven't said I want a specific schema and I select one from the drop down once i'm logged in it tries to create another connection to get the tables where by its password amnesia kicks in again and tells me it can't connect I've not supplied a password

This happens on Fedora 32 (Gnome 3.36.2) with the package from fedora repository version: 0.7.9-1.fc32

**Comment by Alecaddd** [comment]
I don't manage or maintain the package in the Fedora repository, someone else published it and I don't know who.
From what you described, it seems like the `libsecret` library is missing.
I suggest using the flatpak.

**Comment by StuTheBearded** [comment]
I've installed the flatpak version and exactly the same issue is present. Also `libsecret` is installed on my system.
