### ISSUE TITLE
[FLATPAK] Can not open sqlite file using the flatpak app

### ISSUE THREAD

**Issue by williamjmorenor** [Alecaddd/sequeler#333]
Hello I am running sequeler instaled from Flathub on a up to date Fedora 32 system but I can not open the file:

![Captura de pantalla de 2020-05-21 22-12-31](https://user-images.githubusercontent.com/3522386/82630673-ac91b100-9bb0-11ea-8074-c8a59f2609c1.png)

Trying with: flatpak run --filesystem=home com.github.alecaddd.sequeler

And this demo sqlite db: https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

I have the same error:

![Captura de pantalla de 2020-05-21 22-18-23](https://user-images.githubusercontent.com/3522386/82630800-04c8b300-9bb1-11ea-8617-3de7effe6264.png)

Even with:

flatpak run --filesystem=host com.github.alecaddd.sequeler
flatpak run --filesystem=host:ro com.github.alecaddd.sequeler

I have the same error.

**Comment by Alecaddd** [comment]
Hi, thanks for the using Sequeler.
I don't directly manage or support the flatpak version. You should report this issue here: https://github.com/flathub/com.github.alecaddd.sequeler

**Comment by CodedOre** [comment]
I think the problem is a little bigger than just flatpak.

Tested this with the package version on Fedora 32 (Version 0.8.0-1.fc32) and it also there throws an "IO-Error".

**Comment by williamjmorenor** [comment]
From the comment in the flatpak repo it is no related to the flakpat pakaging it selft.
