### ISSUE TITLE
Copy <item> in context menu does not work

### ISSUE THREAD

**Issue by BaileyJM02** [Alecaddd/sequeler#334]
Hello, when right-clicking on a value within a column, and selecting "Copy [column name]" within the context menu, nothing is added to the clipboard, though it is cleared. I believe this means it's actually inputting a null/empty value.

---
Elementary OS 5.1.4 (Hera)
Linux 5.3.0-53-generic
GTK 3.22.30
Sequeler 0.7.91

**Comment by Alecaddd** [comment]
Very strange since I specifically fixed this behaviour in the previous version.
I'll take a look and try to find what's going on.
Thanks for the report.

**Comment by BaileyJM02** [comment]
I’m not sure if you did, it has been broken for me ever since I downloaded it ~2 weeks ago. Didn’t look into reporting it until I realised there was a repo for it today. 👍

**Comment by Alecaddd** [comment]
This was fixed in #330, but I confirm that it doesn't work anymore, darn.
I'll try to fix it later today and release a new version soon, sorry for the trouble.

**Comment by Alecaddd** [comment]
All right, I got confused.
This issue was fixed by #330, but I haven't released a new version yet because I'm finishing up another implementation before packaging v0.8

Sorry for the confusion, this issue is fixed and will be available in the next release.
