### ISSUE TITLE
encode SQLite path

### ISSUE THREAD

**Issue by artemanufrij** [Alecaddd/sequeler#34]
I think path sould be encoded for Entry and Titlebar:
![bildschirmfoto von 2017-10-12 18 53 18](https://user-images.githubusercontent.com/16517095/31508562-c68f86b6-af7e-11e7-8fb4-4b8386577be3.png)

**Comment by Alecaddd** [comment]
That encoded Directory shouldn't appear, it should return a regular string.
Can you write down in detail what you did, and if you can recreate the issue?

**Comment by artemanufrij** [comment]
1. create a new sqlite connection
2. connect to database
3. click on edit button

**Comment by Alecaddd** [comment]
Was the issue solved with the new version?

**Comment by artemanufrij** [comment]
I will check it tonigth
