### ISSUE TITLE
Cannot connect through SSH Tunnel

### ISSUE THREAD

**Issue by rafifos** [Alecaddd/sequeler#341]
I've tested it both using Flatpak and the package that is available at AppCenter.

I need to connect to a database through a tunnel (via AWS EC2). I can connect and execute queries if I start a ssh session with port-forwarding on my terminal, but entering the same settings on the `SSH Tunnel` option somehow doesn't work.

Here's the string that I'm using on the Terminal

```
ssh -i <private key> -N -L 5431:<rds host> ec2-user@<ec2 host>
```

Sequeler log:
```
** (Sequeler:5774): DEBUG: 17:19:37.156: ConnectionManager.vala:156: Opening tunnel 0x5560574dae30
** (Sequeler:5774): DEBUG: 17:19:37.156: ConnectionManager.vala:196: Socket params: <ec2 host> 22
** (Sequeler:5774): DEBUG: 17:19:37.156: ConnectionManager.vala:210: Failed to connect!
** (Sequeler:5774): DEBUG: 17:19:37.156: ConnectionManager.vala:150: Failed to connect!
```

I've tried to change the connection port to 5432, 5431 and 9000 (https://github.com/Alecaddd/sequeler/blob/master/src/Services/ConnectionManager.vala#L184). I've also tried to change the ssh port to 5432 and 5431.

![Captura de tela de 2020-08-07 17 26 45](https://user-images.githubusercontent.com/12601769/89685971-cb603380-d8d3-11ea-8294-06a24d817bc4.png)
![Captura de tela de 2020-08-07 17 27 01](https://user-images.githubusercontent.com/12601769/89685973-cc916080-d8d3-11ea-9963-620e52088dd5.png)

**Comment by Alecaddd** [comment]
I remember having problems with AWS as well in the past.
I'll investigate this issue and see what's up

**Comment by rafifos** [comment]
So, @Alecaddd they changed how I need to access this particular `db`, so for obvious reasons I don't have this issue anymore.

Should I leave it open?

**Comment by Alecaddd** [comment]
We can close it, thanks for the update.
