### ISSUE TITLE
Rounded window corners

### ISSUE THREAD

**Issue by hanaral** [Alecaddd/sequeler#350]
Because elementary 6 thats why
Jokes aside, the elementary style seems to be going that way, It would be pretty cool to see sequeler adopt it too.
The official apps and some others seem to be using Hdy.Window as an easy and consistent way of applying it througout. The corner radius elementary uses is a part of the new stylesheet afaik so that shouldnt be an issue.

Thanks for inspiring me to make the icon of Olifant!

**Comment by Alecaddd** [comment]
Sequeler already uses the elementary stylesheet by default, and also the flatpak bakes the stylesheet in it, so once elementary OS 6 is released, I'll release a new version of Sequeler with the updated dependencies.
Cheers
