### ISSUE TITLE
Flatpak manifest in source tree out of date

### ISSUE THREAD

**Issue by wjt** [Alecaddd/sequeler#353]
I tried to build this app in GNOME Builder to debug whether to blame a crash I see on Sequeler or on libgda, but the manifest in this repo references version 3.30 of the GNOME runtime. The app I have installed from Flathub uses `org.gnome.Platform/x86_64/3.36`, so I think the in-tree one must have drifted out of date.

**Comment by Alecaddd** [comment]
Maybe @bilelmoussaoui can take a look at this if he has some free time :D

**Comment by bilelmoussaoui** [comment]
Sure, I will have a look tonight
