### ISSUE TITLE
Refine Library interaction

### ISSUE THREAD

**Issue by cassidyjames** [Alecaddd/sequeler#36]
I can't imagine when someone would add a connection to their library, and then not want to see it on the welcome screen. However, showing the library at all times seems a bit excessive. I propose:

- Show the Library on the welcome screen as long as there is a connection in the library
- Don't show the library sidebar once connected to a database

**Comment by cassidyjames** [comment]
This also lets you drop a preference and test case :wink:

**Comment by Alecaddd** [comment]
Great!
I was actually already working on this UI refactor, completely drop the Library view, and use the side panel to show the list of tables once a connection is open.
Thanks for the suggestion!

**Comment by Alecaddd** [comment]
Library refactored.
Will publish it in the upcoming `v0.3.0` release, that should happen this weekend.

![New Library](https://github.com/Alecaddd/sequeler/blob/dev/sequeler-screenshot.png)
