### ISSUE TITLE
How can I make Sequeler work with a docker mysql container instance?

### ISSUE THREAD

**Issue by jsmsalt** [Alecaddd/sequeler#37]
Is this possible? I tried to create commands that interact with the mysql commands of the container from the outside, but it doesn't work. The app is showing the message "No provider 'MySQL' installed".

**Comment by caioguedes** [comment]
I think it's not possible now. But, I really want thing like that in Sequeler.

**Comment by Alecaddd** [comment]
Most likely you're missing a library you can install with `sudo apt-get install libgda-5.0-mysql`.
This is a known issue with the Gda dependencies I'm trying to solve.
Closing this issue because it's a duplicate of #26
