### ISSUE TITLE
Refactor Connection and Query to async methods

### ISSUE THREAD

**Issue by Alecaddd** [Alecaddd/sequeler#40]
The UI and entire application freeze when a query or a connection takes more than few seconds to execute.

**Comment by artemanufrij** [comment]
you need something like this:
```
    public int run_query (string query) {
        try
        {
            new Thread <void*> (null, () => {
                var result = db.run_query (query);
                Idle.add (()=>{
                    output_query = result;
                    return false;
                });
                return null;
            });
        }
        catch (Error e)
        {
            query_error (e);
        }
        return output_query;
    }
```

**Comment by Alecaddd** [comment]
@artemanufrij Thank you so much for your suggestion. Yes, indeed this approach allows the query to be run asynchronously. The problem is that the rest of the script gets the first `return null` before anything else, and trigger the `Unable to process Query` message.
After the `idle` is completed, the method doesn't return the correct result.

I'm still trying to grasp the concept of async methods in Vala, and I'm sure I'm missing something super obvious T_T

**Comment by Alecaddd** [comment]
@artemanufrij I released on the `dev` branch the initial refactor for async methods. Right now I'm handling only the connection from the open dialog.
Can you take a look at what I did and tell me if you think there's a better approach?
It feels like an exaggerated amount of code.

**Comment by artemanufrij** [comment]
It looks good, but why do you wait for a second in line 219?

**Comment by Alecaddd** [comment]
@artemanufrij Hey man, sorry to bother you, I just pushed to the dev branch the full refactor to handle all DB queries as async methods.
Would you be able to download it and compile it from source to test it?
It runs super smoothly and works perfectly for me, but I would love to have a quick double check before pushing it to the AppCenter.
Cheers

**Comment by artemanufrij** [comment]
@Alecaddd yes, I'm going to test it tonight

**Comment by artemanufrij** [comment]
@Alecaddd sequeler craches instantly when I'm trying following statement:
`select * from tracks`. Tracks has ~6000 rows.

[database.db.zip](https://github.com/Alecaddd/sequeler/files/1443960/database.db.zip)

**Comment by Alecaddd** [comment]
@artemanufrij it looks like there's something wrong with the `duration` data in your `tracks` table.
If I manually select all the tables except `duration`, the query runs perfectly and prints out all the results.

!(query)[https://i.imgur.com/6Ku55M3.png]

If I run just the following query `SELECT duration FROM tracks`, the app crashes immediately.
What type of data is stored in that column? Any chance it's corrupted or doesn't match the column type?

**Comment by artemanufrij** [comment]
@Alecaddd here is CREATE TABLE stipped. It's just an integer. I can open and edit this table without issues with Sqliteman.
`
CREATE TABLE IF NOT EXISTS tracks (
                ID          INTEGER     PRIMARY KEY AUTOINCREMENT,
                album_id    INT         NOT NULL,
                path        TEXT        NOT NULL,
                title       TEXT        NOT NULL,
                genre       TEXT        NULL,
                track       INT         NOT NULL,
                disc        INT         NOT NULL,
                duration    INT         NOT NULL,
                CONSTRAINT unique_track UNIQUE (path),
                FOREIGN KEY (album_id) REFERENCES albums (ID)
                    ON DELETE CASCADE
`

**Comment by artemanufrij** [comment]
@Alecaddd try to use `int64` instead `int`

**Comment by Alecaddd** [comment]
@artemanufrij I'm working on a better column type detection for the results generation, this should fix the issue you're experiencing with your data.
I'm closing this issue because the async methods have been implemented.
