### ISSUE TITLE
Database name is not shown [GUI BUG]

### ISSUE THREAD

**Issue by ar0ra1** [Alecaddd/sequeler#42]
![seq](https://user-images.githubusercontent.com/20777462/31796651-442b0d7e-b548-11e7-9b4e-0e43d0b1bd6c.png)

**Comment by Alecaddd** [comment]
Are you using a tweaked Gtk theme? This never happened before.
Can you activate the Gtk CSS inspector and see if the name of the DB is there but just white?
Does it show with the Dark Theme option?

Anyway, I completely rebuilt the Library and I will release the new version this weekend. That UI doesn't exist anymore.
Cheers

**Comment by ar0ra1** [comment]
I cloned it and installed 
the port field came along 

Guess you are right,
its the themes fault,
any other theme apart from the default and high color doesn't show the name!

**Comment by Alecaddd** [comment]
Ok, that's good to know.
I will close this issue for now and see if it gets solved with the new UI.
Feel free to reopen it if the issue persists.

BTW, what Gtk Theme are you using? It looks super slick 😃

**Comment by ar0ra1** [comment]
Theme -
https://github.com/LinxGem33/OSX-Arc-Darker

Will switch to this - if the GUI i just posted gets fixed  :)
https://github.com/btd1337/eOS-Sierra-Gtk
