### ISSUE TITLE
Multiples tables at sidebar

### ISSUE THREAD

**Issue by caioguedes** [Alecaddd/sequeler#44]
When I enter in a saved connection and logout of this, and again enter in the same or other connection, the tables sidebar are accumulating panels. Maybe need to recreate instance of `DataBaseOpen` or clean the `sidebar_table` when a new connection is opened.

![screenshot from 2017-10-20 09 47 31](https://user-images.githubusercontent.com/2953198/31819677-7be1f5fa-b57c-11e7-8707-c984f95dfe89.png)
This is when I open and close multiples connections from library.

**Comment by ar0ra1** [comment]
Same!

**Comment by Alecaddd** [comment]
Yes, I forgot to empty the view on logout.
Releasing an update right now!

**Comment by Alecaddd** [comment]
Fixed on recent commit
