### ISSUE TITLE
[SQLite Error] information_schema.TABLES 

### ISSUE THREAD

**Issue by artemanufrij** [Alecaddd/sequeler#46]
![bildschirmfoto von 2017-10-21 23 54 37](https://user-images.githubusercontent.com/16517095/31856183-643ef0c0-b6bb-11e7-8cc8-769a0812a2d8.png)

**Comment by Alecaddd** [comment]
Thanks for the report, I didn't consider the SQLite limitation.
Will publish a fix soon.
