### ISSUE TITLE
DataBase Tables Sidebars empty in PostgreSQL

### ISSUE THREAD

**Issue by alexandremagro** [Alecaddd/sequeler#47]
DataBase Tables Sidebars seems not to be working in PostgreSQL.

**Comment by Alecaddd** [comment]
Can you be more specific?
Please attach a screenshot of your empty tables, let me know if you're connecting to a local or remote DB, etc.
The more I know, the quicker I can fix the issue :smile:

**Comment by alexandremagro** [comment]
#### Config:
![sequeler-config-error](https://user-images.githubusercontent.com/2325938/31895201-4e61b1d6-b7ef-11e7-9af4-f87836c819fa.png)

#### Error:
![sequeler-error](https://user-images.githubusercontent.com/2325938/31895029-e2f2ea50-b7ee-11e7-88e1-f1bb91b8663d.png)

@Alecaddd do you think I should open another Issue, since you closed that one?

**Comment by Alecaddd** [comment]
@alexandremagro thank you so much for your extra info.
I closed it because I released v0.3.4 that should fix this issue. It should be available on the AppCenter later today, feel free to reopen this issue if the problem persists after the update.
Cheers
