### ISSUE TITLE
Settings schema does not contain a key named 'tot-connections'

### ISSUE THREAD

**Issue by mukarramkhalid** [Alecaddd/sequeler#48]
Since the last release, I'm getting this error.

> [ERROR 03:10:48.673324] [GLib-GIO] Settings schema 'com.github.alecaddd.sequeler' does not contain a key named 'tot-connections'

I think it's because of the changes you made here c6322d84f41637ab7f93761bd09313582160e9c4.

**Comment by Alecaddd** [comment]
Sorry, that was a stupid mistake.
Releasing a fixed version right now

**Comment by mukarramkhalid** [comment]
No problem. Keep up the good work. :)
