### ISSUE TITLE
[PostgreSQL] Tables Sidebars showing wrong table names

### ISSUE THREAD

**Issue by alexandremagro** [Alecaddd/sequeler#52]
The table names are displaying the name of my database, probably getting info of wrong column, at least in PostgreSQL.

![tablename-error](https://user-images.githubusercontent.com/2325938/31961693-41d089c4-b8da-11e7-9219-a6f5b32ee7cf.png)

**Comment by Alecaddd** [comment]
Thanks for the report.
PostgreSQL has many columns separated by a different schema name, sometimes the user wants to retrieve specific columns instead of others.
I'm working on a drop-down selection to allow you to pick the tables you want to visualize, grouped by `schemaname`

**Comment by alexandremagro** [comment]
Still broken after 0.3.4 (`Display Table lists for SQLite and PostgreSQL`)
All Table List show a list with my database name (`cpm_development`).

Why you don't try the query in my first image report? There I get the name of the tables correctly

![still-broken](https://user-images.githubusercontent.com/2325938/32694486-2c8c34d0-c728-11e7-9c7f-4ca45557923c.png)

**PS:** The second line of the menu is loud and ugly. Control (Structure | Query) could replace the title.

**Comment by Alecaddd** [comment]
@alexandremagrodid you update to `v0.4`? I added the ability to select which table schema to show.
Still broken?

**Comment by alexandremagro** [comment]
@Alecaddd Yes, this screenshot is from version `v0.4`. And all the options in the selector, either it shows an empty list, or a list with all elements with the name of my database.

I think you should consider this query:

```sql
SELECT tablename FROM pg_catalog.pg_tables
WHERE schemaname != 'information_schema' AND schemaname != 'pg_catalog';
```

**Comment by Alecaddd** [comment]
I pushed your code to the dev branch. Can you compile the source and tell me if it works?
After updating some packages, I can't seem to connect to my local PostgreSql database anymore. It keeps saying `no provider 'postgresql' installed`. So annoying >_>

**Comment by Alecaddd** [comment]
@alexandremagro Pushed a new version with this fix, can you confirm it's working properly?

**Comment by alexandremagro** [comment]
Sidebar is correct.

But, when I select a table, this show it's metadata table, is this the expected behavior?

**OBS:** All options in selector shows the same thing.

![sequeler-error-2](https://user-images.githubusercontent.com/2325938/33619626-dd700716-d9cc-11e7-9045-94ab3b0b9c6b.png)

**Comment by Alecaddd** [comment]
Yep, it's correct. The table structure tab should show the table's metadata.
Cool, everything seems to be working, thanks for the feedback.
Closing this issue
