### ISSUE TITLE
Non-selection querys don't work

### ISSUE THREAD

**Issue by Philip-Scott** [Alecaddd/sequeler#53]
### What's happening: 
Running a non-select query such as `show schemas` does not run, with the following error:

![image](https://user-images.githubusercontent.com/10786508/32021787-0ae26fca-b99a-11e7-9290-034493adec92.png)

### Expected results
It should still execute the command, and show the output even as just "plain text" on the output section

**Comment by Philip-Scott** [comment]
Same thing happens if you run an update and then a Select on the same query :)

**Comment by Alecaddd** [comment]
That's an issue with the `GDA` library that needs to handles raw query with 2 different methods:
* `execute_non_select_command()` => returns an INT based on the number of rows affected
* `execute_select_command()` => returns a Gda.DataModel

Right now, I'm matching the existence of the word `SELECT` in the query to use the proper command, but as you noticed, it's not bullet proof.
Do you have any recommendation?

**Comment by Philip-Scott** [comment]
Hmmm.... you could maybe do a regex split on `;` that are not contained in quotes to separate the querys, but i think that could bring problems with something like stored procedures :thinking:

**Comment by Alecaddd** [comment]
Pushing a new version with the fix for this issue later tomorrow!
