### ISSUE TITLE
Clicking on a table name should insert it into the query text

### ISSUE THREAD

**Issue by Philip-Scott** [Alecaddd/sequeler#55]
For quick prototyping :)

**Comment by Alecaddd** [comment]
Mh, not sure about this.
I'm currently building a paned UI that visualizes the table schema, data, and other info when you click on a table name.
I wouldn't use the table list to populate the query.

A future idea is to implement the table list as an autocomplete/suggestion while typing the query.

**Comment by Philip-Scott** [comment]
Feel free to close issues you don't think belong :) Another option could be to get the table schemas, and suggest autocompletion like Scratch does

**Comment by Alecaddd** [comment]
Yup, that's all part of the plan 😃 
Thank you so much

**Comment by Philip-Scott** [comment]
you shouldn't close issues if you're going to work on it until it's actually solved :) That way, people interested in the feature/bug can track the issue here instead of filing it again. 

same for #54

**Comment by Alecaddd** [comment]
@Philip-Scott You're right, thanks for the feedback.

**Comment by artemanufrij** [comment]
IMO, it would be ok to insert a `select * from [clicked table]`

**Comment by Alecaddd** [comment]
Clicking on the table now shows the table structure in the Structure Tab.
Moving forward, this section will be extended to show the full schema, table size, and various info.
Closing the issue
