### ISSUE TITLE
View query error details

### ISSUE THREAD

**Issue by jonasdiel** [Alecaddd/sequeler#57]
When the query returns an error, it does not appear on the screen. This makes it difficult to identify the problem.

![erro](https://user-images.githubusercontent.com/2653078/32984667-fc159688-cc91-11e7-9379-3c1de1ccde68.png)

On the terminal occurs:

> integracao=# select 1 from nothing;
ERRO:  relação "nothing" não existe
LINE 1: select 1 from nothing;
                      ^
integracao=#

Using PostgresSQL I also detected the problem already reported in #52

**Comment by Alecaddd** [comment]
@jonasdiel thanks for the report. A better handling of error messages is coming in the next version of Sequeler.

**Comment by Alecaddd** [comment]
v0.4.1 addresses this issue by printing the error message in the message toolbar.
