### ISSUE TITLE
GUI Bug with Structure

### ISSUE THREAD

**Issue by ar0ra1** [Alecaddd/sequeler#58]
So, I had the table name `orders` in 2 different databases.
But it still shows me both with the `structured option` 

![screenshot from 2017-11-28 18-50-05](https://user-images.githubusercontent.com/20777462/33322063-ea8e3170-d46d-11e7-8aa7-cd657666d9f4.png)

PS - Screenshot is little horrible, can't help it. NDA's don't allow me to post tables openly :P

**Comment by Alecaddd** [comment]
Thanks for the report, I'll add a fix for this in the next release.
