### ISSUE TITLE
A long error message on the query viewer hides the Run button

### ISSUE THREAD

**Issue by Philip-Scott** [Alecaddd/sequeler#64]
Looks like you might need to wrap that label :) 

a `label.warp = true` seems to fix it, and you might need to add a Gtk.Align.START to the run button to prevent it from expanding 

![screenshot from 2017-12-04 16 42 55](https://user-images.githubusercontent.com/10786508/33580351-7c64375e-d912-11e7-9eb7-d5703aeaf222.png)

**Comment by Alecaddd** [comment]
Thanks for the report, totally forgot about the warp option.
I'll add it immediately
