### ISSUE TITLE
Selecting a database doesn't change where the query executes from

### ISSUE THREAD

**Issue by Philip-Scott** [Alecaddd/sequeler#65]
In the following example, i have the database `information_schema` selected and there it shows that a table call VIEWS exists, but when trying to run a select the error message says that the table `startupgdl.VIEWS` does not exist. 

In other words, it looks like selecting a database doesn't execute the `use` command :) 

Note: startupgdl IS another database inside this host

![screenshot from 2017-12-04 16 48 34](https://user-images.githubusercontent.com/10786508/33580493-0996ba20-d913-11e7-984a-971053be7ebc.png)

In case this matters, i'm using mysql as the database server :)

**Comment by Alecaddd** [comment]
That's right, selecting the database doesn't change the actual DB the `LibGda` is currently connected to. I guess `startupgdl` is the database name you specified in the connection dialog, and the query is using that by default.
I'll add this fix to the next release, thanks!

**Comment by Alecaddd** [comment]
Darn, now I remember why I didn't implement this at the beginning.
It looks like the `Gda.Connection` doesn't support the `use` statement. When I try, I get this error
```
this command is not supported in the prepared statement protocol yet
```
I guess the solution would be to close the current connection and open a new one with the selected database from the dropdown, but I'm not sure about this workflow.

**Comment by ar0ra1** [comment]
that's why I asked you  on twitter regarding this, 
it makes no sense at all. 
All this feature allows to do is to the see the name of the table and nothing else, the structure also isn't shown!

**Comment by Alecaddd** [comment]
I know, it's a pretty annoying limitation of the LibGDA.
I'll try this week to handle a close and reopen connection when you select a different database, and auto select the DB you connected to from the dropdown when you open the connection from the first time.

**Comment by Alecaddd** [comment]
I just pushed version `0.5.0` that should fix this problem.
Please, update the app and let me know if it's fixed.

**Comment by Philip-Scott** [comment]
I'll make sure to test it tomorrow at the office! :) Thank you so much for your work man!

**Comment by Alecaddd** [comment]
Any news about this. For me it's fixed and can handle switching between multiple database :smiley:

**Comment by adlersd** [comment]
I'm using from the source code and it is working properly.

**Comment by Philip-Scott** [comment]
@Alecaddd I totally forgot to close it! :sweat_smile: But it's good! I've been using it a lately without a problem :)
