### ISSUE TITLE
Allow connection over SSH

### ISSUE THREAD

**Issue by Lewiscowles1986** [Alecaddd/sequeler#68]
Some setups will need to connect via SSH

![mysql-via-ssh](https://user-images.githubusercontent.com/2605791/34512596-6c4d1510-f05b-11e7-8467-fed18cd0db61.png)

The screenshot is of MySQL WorkBench, which is opensource. I'm pretty sure it establishes a tunnel, then uses that tunnel as a proxy. The benefit is an encrypted connection to database, and support for connecting to security-conscious environments.

**Comment by Alecaddd** [comment]
Hi, thanks for the request.
An SSH gateway is scheduled for version`1.0`, not sure when I'll be able to do it, but it's on the list of upcoming features 😄

**Comment by Alecaddd** [comment]
Closing because duplicate of #33

**Comment by Lewiscowles1986** [comment]
Apologies for posting a duplicate
