### ISSUE TITLE
GTK3 issue?

### ISSUE THREAD

**Issue by pavlepiramida** [Alecaddd/sequeler#69]
HI Alessandro,
Im using you majestic app on Arch running Gnome3.26 and I noticed some strange things

Example:
![image](https://user-images.githubusercontent.com/18991480/34541312-0339b0e2-f0d8-11e7-88a7-1fd40ce40e27.png)
You can notice that strange black frame around header.

This is happening with almost all (screenshot was made with gnomes stock theme,Adwaita-Dark) themes,except Arc-gtk-theme.

If there is anything I could do to fix this please let me know.I really adore Sequeler and would very much like to continue using it on other linux distributions as well!

**Comment by Alecaddd** [comment]
Uh, thanks for the report. Which version of Gtk are you currently running?
It could be an issue with the `margin` option of the GTK headerbar.
What version of Granite are you running?

**Comment by pavlepiramida** [comment]
Compiled against:
gtk3-3.22.26+47+g3a1a7135a2-3
granite-0.5-1

**Comment by Alecaddd** [comment]
I've never compiled it against a Gtk version higher than 3.18
I'll test it later and let you know

**Comment by Alecaddd** [comment]
I confirmed the nature of the problem and i know how to fix it.
Basically, it's all related to the crappy approach I used to make the headerbar grow by injecting a second box in it. Terrible decision 😅
I'm starting a code refactor and I should be able to fix everything

**Comment by Alecaddd** [comment]
I just pushed version `0.5.0` that should fix this problem.
Please, update the app and let me know if it's fixed.

**Comment by pavlepiramida** [comment]
@Alecaddd Its working like a charm now,kudos for the work!
