### ISSUE TITLE
Snap won’t run on Fedora (libgda version conflict)

### ISSUE THREAD

**Issue by da2x** [Alecaddd/sequeler#74]
sequeler 0.4.1, Fedora 27, snapd 2.29.4-3, libgda 5.2.2-11

> $ snap run sequeler
> /snap/sequeler/122/usr/bin/com.github.alecaddd.sequeler: error while loading shared libraries: libgda-5.0.so.4: cannot open shared object file: No such file or directory

**Comment by Alecaddd** [comment]
Thanks for the report, I'll look into it

**Comment by bartzaalberg** [comment]
Some here on elementaryOs

**Comment by Alecaddd** [comment]
I'm not currently actively supporting the snap version, so you shouldn't use it.

@bartzaalberg did you install Sequeler form the AppCenter?

**Comment by bartzaalberg** [comment]
Yes and that is working perfectly actually :P But i was trying to get my own applications into a snap. But that didn't work. So i thought. How did sequeler do it? And then i noticed that i didn't work so i reported it. So long story short. I use the appcenter version :P

**Comment by Alecaddd** [comment]
@bartzaalberg oh well, if you figure out how to make it work, please let me know XD
My snapcraft setup compiles and builds everything without errors, but as you saw, the app doesn't run properly and I've no idea why.

I'll remove it for now and don't offer it as I don't have time or the knowledge to support it.

**Comment by bartzaalberg** [comment]
I will probably do the same. But if i do find out more. I will let you know!

**Comment by babluboy** [comment]
I’m trying to set up a snap for my ebook reader (Bookworm)...however I’m running into issues with granite 0.5 and webkit2...I will check your snapcraft to see how you are building granite and see if it works

**Comment by Alecaddd** [comment]
@babluboy Unfortunately, I was never able to make my snapcraft file and building process work.
Many issues with missing libraries or inability to properly install the `.desktop` file, resulting a failed snap installation.

**Comment by secmohammed** [comment]
any solution yet ? , I'm facing the same problem on debian.

```
snap run sequeler 

```
/snap/sequeler/122/usr/bin/com.github.alecaddd.sequeler: error while loading shared libraries: libgda-5.0.so.4: cannot open shared object file: No such file or directory

libgda version : 5.2.4-11

**Comment by Alecaddd** [comment]
I deleted the Snap version a long time ago, I'm not sure how is this still available. Sequeler doesn't currently have a Snap version created or maintained by me.
There's a FlatPak available that it's maintained, updated, and fully working.
