### ISSUE TITLE
App crashes when executing select statment

### ISSUE THREAD

**Issue by cjfloss** [Alecaddd/sequeler#75]
Executing
`select * from transactions`
in the database from [**envelope**](https://github.com/cjfloss/envelope) the app just crashes

**Comment by Alecaddd** [comment]
Hi, thanks for the report. I'm currently working on a full rewrite of the app to avoid these sudden crashes when dealing with unrecognized data.
Sorry for the issue

**Comment by cjfloss** [comment]
Ok, just for the record this is the structure of the database

It's a SQLite database

```
CREATE TABLE IF NOT EXISTS transactions (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT,
                `label` TEXT NOT NULL,
                `description` TEXT,
                `direction` INT NOT NULL,
                `amount` DOUBLE NOT NULL,
                `account_id` INT NOT NULL,
                `category_id` INT,
                `parent_transaction_id` INT,
                `date` TIMESTAMP NOT NULL,
            FOREIGN KEY (`parent_transaction_id`) REFERENCES `transactions`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
            FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE CASCADE ON DELETE SET NULL,
            FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE CASCADE ON DELETE CASCADE)
```

**Comment by Alecaddd** [comment]
Can you try to select all the columns except the date? 
`select id, label, description, direction, amount, account_id, category_id, parent_transaction_id from transactions`

And if this also crashes, could you try selecting one by one and tell me which column causes the crash?

**Comment by cjfloss** [comment]
It works great, only running `select date from transactions` crashes.

**Comment by Alecaddd** [comment]
Damn, I knew it!
Not sure why but the way I set the generation of the `Gtk.TreeView` model, crashes when handling `TIMESTAMP` formats.
Ok, thanks for the feedback, I'll work on that!

**Comment by cjfloss** [comment]
The error occurs at TreeBuilder#39 `store.set_value (iter, i, _iter.get_value_at (i));`

I replace it for
> try {
>     store.set_value (iter, i, _iter.get_value_at_e (i));
> } catch (Error e) {
>     print("Error %d: %s\n",e.code, e.message);
> }

and I get get the message
`Error 10: Invalid timestamp '1516244400' (format should be YYYY-MM-DD HH:MM:SS[.ms])`
`Error 10: Invalid timestamp '1516244400' (format should be YYYY-MM-DD HH:MM:SS[.ms])`

**Comment by Alecaddd** [comment]
Thank you so much!
I'll review your PR and merge it when I'm back home.

**Comment by Alecaddd** [comment]
Pushed your fixes to AppCenter, and also printing the error in the query bar.
Thanks for your help!
