### ISSUE TITLE
Path problem seems fixed, but only if Sequeler is reopened after pressing logout with sqlite

### ISSUE THREAD

**Issue by rasmus91** [Alecaddd/sequeler#77]
The problem [Here](https://github.com/Alecaddd/sequeler/issues/72) seems to persist. That is: if i logout of the Sqlite database, and then doubleclick it again, i get the same error message. But if i then close down sequeler, and open it again, there's no problem logging in. Until i logout of the DB again, and try reconnecting.

**Comment by Alecaddd** [comment]
Hey, sorry I should've specified it in the other issue. The fix has been pushed to v0.4.3, currently in review before getting published on the AppCenter.
Which version are you currently running?

**Comment by rasmus91** [comment]
0.4.1, the one from AppCenter. I'll make sure to report if i run across it again after I can upgrade to 0.4.3.

**Comment by Alecaddd** [comment]
Thanks, and sorry again for the annoying issue.

**Comment by Alecaddd** [comment]
0.4.3 is out and it fixed the problem for me. I'll wait for your confirmation before closing this issue.

**Comment by rasmus91** [comment]
Consider this your Confirmation mate :)

It works very well, thank you so much for this smooth and beautiful app. I would suggest adding Sql Server (MS) support also, I know it's not OS, but then they did release it for Linux, and it is a very popular platform.

**Comment by Alecaddd** [comment]
Sweeeeeeeet! Finally, it seems like I'm starting to understand Vala.
I'm currently rebuilding Sequeler from scratch to open up a sort of Providers API to let everyone contribute queries for any type of database, not sure it'll work, but let's see 😀

**Comment by rasmus91** [comment]
Oh Sure, why not? :)

Usually I've found that simple in Sql Browsers/Editors really means: poorly designed, but yours is quite contrary. Keep up the good work. :+1:
