### ISSUE TITLE
Cannot connect to remote host, always tries localhost

### ISSUE THREAD

**Issue by BaronVonPerko** [Alecaddd/sequeler#78]
I set the host to the remote server IP, but when I test connection, it says connection failed for user 'myuser'@'localhost'.

**Comment by Alecaddd** [comment]
Argh, that never happened.
Is your remove host protected via SSH?
Did you try saving your connection before trying to connect?
Does this happen also if you click on `Test Connection`?

**Comment by BaronVonPerko** [comment]
Yes it was when I was using the "test connection". It may have been an she protection, it was a client's machine. I'll test it with my own server tomorrow and get back to you

**Comment by BaronVonPerko** [comment]
Turns out that the client's machine was refusing remote connections like you said.  However, the error message is still misleading.  If I get some time, I will try to figure it out and create a PR :)

**Comment by Alecaddd** [comment]
Interesting. The error message is automatically returned by the `LibGda`, I didn't write that manually. Not sure why is not using the proper credentials in the warning.

I'm almost done the refactoring of the app, when I reach that section, I'll see if I can improve it.

**Comment by Alecaddd** [comment]
I just pushed version `0.5.0` that should fix this problem.
Please, update the app and let me know if it's fixed.

**Comment by BaronVonPerko** [comment]
This is now working correctly :+1: Nice work!
