### ISSUE TITLE
could you make a flatpak for sequeler?

### ISSUE THREAD

**Issue by altntowin** [Alecaddd/sequeler#79]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for sequeler?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by Alecaddd** [comment]
Hi, thank you so much for the request.
I'd love to do that, but I'm not sure I'm capable.
I've been trying to release Sequeler as an AppImage or Snap for quite sometimes without success.
I've been having issues with library versions and properly setting up the desktop file.
I'm not an expert and this is my first Linux app. Would you or someone else be able to help?

I'll try to look into it and see if it's an easy process.

**Comment by altntowin** [comment]
i see , but maybe you could try with flatpak ,  i think is more easier than snap and appimage.
I would like to help you, but I do not know programming .
here you can find information about flatpak 
https://flatpak.org/
developer guide : 
http://docs.flatpak.org/en/latest/

i hope you can solve the problem, and make the application
thanks.

**Comment by bil-elmoussaoui** [comment]
I can help getting the flatpak package to flathub ;)

**Comment by Alecaddd** [comment]
I'm almost done refactoring Sequeler with a lighter and cleaner code base, and a couple of new features. After that, I'll jump on packaging it as Snap, Flatpak, and Appimage for everyone to use it.
Thanks for your help and interest!

**Comment by Alecaddd** [comment]
I tried to build a flatpak but I haven't succeeded as I'm encountering issues with the packages I'm using.
Unfortunately, I don't have the time or knowledge the support it and troubleshoot it. If you guys want, feel free to fork it and package it by yourself, and hopefully you can succeed where I failed >_>

**Comment by bil-elmoussaoui** [comment]
@Alecaddd Which issues you had?

**Comment by bilelmoussaoui** [comment]
I can work on it if you need some help on flatpak packaging !

**Comment by bilelmoussaoui** [comment]
Here you go
https://github.com/flathub/flathub/pull/316

**Comment by bilelmoussaoui** [comment]
Already on flathub.
