### ISSUE TITLE
Bug when open MariaDB database

### ISSUE THREAD

**Issue by btd1337** [Alecaddd/sequeler#81]
This error is ocurring in MariaDB database:

![screenshot from 2018-02-13 16 39 27](https://user-images.githubusercontent.com/11943860/36167401-eaff7fc8-10dc-11e8-9046-3e94bc6fbd76.jpeg)

Opening for the first time
![screenshot from 2018-02-13 16 39 10](https://user-images.githubusercontent.com/11943860/36167417-f6fa9d08-10dc-11e8-8981-50272d97aeee.jpeg)

Opening again
![screenshot from 2018-02-13 16 39 50](https://user-images.githubusercontent.com/11943860/36167432-027e8694-10dd-11e8-8952-6bfa3300aee3.jpeg)

First Query: Error Message
![screenshot from 2018-02-13 16 40 01](https://user-images.githubusercontent.com/11943860/36167449-0f22bff0-10dd-11e8-9fdf-c0a52d5cf4d4.jpeg)

Trying to set db: Error Message
![screenshot from 2018-02-13 16 40 15](https://user-images.githubusercontent.com/11943860/36167458-175e0da0-10dd-11e8-8633-291fa6d5fb6c.jpeg)

Trying to run query again it's ok
![screenshot from 2018-02-13 16 40 24](https://user-images.githubusercontent.com/11943860/36167485-2b1e9d8c-10dd-11e8-97b1-28fe29993ef5.jpeg)

But structure is not being displayed
![screenshot from 2018-02-13 16 40 29](https://user-images.githubusercontent.com/11943860/36167491-30febb60-10dd-11e8-9af8-35cfc676f067.jpeg)

It's possible fix this?

**Comment by Alecaddd** [comment]
Hi, thanks for the report.
This is an issue that I'm fixing for the next version of Sequeler, currently in development.
Basically, when selecting a Database from the drop-down, `LibGDA` is not able to set that database as the currently used, as you noticed also by trying to use the command `use "name";`, is not supported by the library.
To quickly solve this issue, insert the name of the Database, in your case `lend`, in the connection Dialog.

**Comment by Alecaddd** [comment]
I just pushed version `0.5.0` that should fix this problem.
Please, update the app and let me know if it's fixed.

**Comment by btd1337** [comment]
This error has been corrected but he generated another error.

**MariaDB running in docker**

![screenshot from 2018-02-19 14 08 49](https://user-images.githubusercontent.com/11943860/36389732-ff291a58-157e-11e8-84ba-53e5fdd4a32d.jpeg)

Apparently in Postgres you do not need to run the use Database command. I can't tell if it also occurs with MySQL.

**Postgres**

![screenshot from 2018-02-19 14 09 00](https://user-images.githubusercontent.com/11943860/36389858-7d88fd1e-157f-11e8-9718-18840e145755.jpeg)

![screenshot from 2018-02-19 14 09 42](https://user-images.githubusercontent.com/11943860/36389866-83b95288-157f-11e8-8b4c-0f3810b45c9f.jpeg)

**Comment by Alecaddd** [comment]
Closing this because the original issue has been solved.
You already opened a new issue, thanks.
