### ISSUE TITLE
Bug when open Postgres database

### ISSUE THREAD

**Issue by btd1337** [Alecaddd/sequeler#82]
The last version generated an error in the Postgres.

![screenshot from 2018-02-19 14 09 00](https://user-images.githubusercontent.com/11943860/36389938-d5c6fc24-157f-11e8-97e8-347012f96d43.jpeg)

![screenshot from 2018-02-19 14 09 42](https://user-images.githubusercontent.com/11943860/36389942-d9a30928-157f-11e8-9d1e-c034503111dc.jpeg)

Maybe putting a switch (database type) will solve the problem.

```
switch(database) {
    case 'postgres': ...
    case 'mariadb': ...
    case 'mysql': ....
    default: ...
}
```

**Comment by Alecaddd** [comment]
Great, I'm a PRO at adding bugs!
The code already switches methods and options based on the selected database type.
I forgot to fully test PostgreSql for the table change feature, silly me.
I'll fix that and push an update.
Cheers

**Comment by btd1337** [comment]
Has not yet been fully corrected.

Now database is connected but the tables aren't displayed.

![screenshot from 2018-02-21 04 40 29](https://user-images.githubusercontent.com/11943860/36468417-13e92a3e-16c2-11e8-9224-9cc1e1512308.jpeg)

It's necessary to click in Refresh button to display the tables correctly.

![screenshot from 2018-02-21 04 40 39](https://user-images.githubusercontent.com/11943860/36468459-30abbed4-16c2-11e8-9738-4d61883eb0af.jpeg)

Other bug happens when other database is selected.

![screenshot from 2018-02-21 04 41 42](https://user-images.githubusercontent.com/11943860/36468504-631c5c02-16c2-11e8-9336-547d892ad982.jpeg)

The old data is kept. Reopen this issue please.

**Comment by Alecaddd** [comment]
Could you run this command in your terminal and paste here the results?
`dpkg -l | grep postgres`

Cheers

**Comment by btd1337** [comment]
Formated output:

![screenshot from 2018-02-22 14 51 13](https://user-images.githubusercontent.com/11943860/36555115-df4fd4c0-17df-11e8-9e5f-8e8274b3183d.jpeg)
