### ISSUE TITLE
how update column with ui ?

### ISSUE THREAD

**Issue by ho3ein-mola** [Alecaddd/sequeler#84]
First thanks for this great project :+1: 
Secend : for example i have active column and its value = 1 and i try to make it 0 is there any UI solution for this or i should use query ?

**Comment by Alecaddd** [comment]
Thanks for using Sequeler.
For now, you have to use the query, unfortunately. I'm slowly adding features to do everything via the UI.
Already right now, you can update the name of a table by double-clicking on it and entering a new name.
Not sure when I'll be able to release these features, but that's the goal of Sequeler 😄

**Comment by ho3ein-mola** [comment]
I have suggestion, add section to store query to use them more that 1 time i think it easier to implement .
and you can close this topic btw.

**Comment by Alecaddd** [comment]
Uh, that's an interesting addition.
Maybe a history tab that saves all your previously used Queries. Something like a browser history.
Great suggestion, thank you so much!
