### ISSUE TITLE
Sequeler crashes after creating a new connection and selecting database

### ISSUE THREAD

**Issue by stefpankov** [Alecaddd/sequeler#85]
In the create new connection process, after entering all required information, passing the connection test and clicking on connect, I'm presented by the "connected to Connection Name" screen and am asked to select the database from the dropdown list even tho I already entered the database name previously.

After selecting the database, sequeler just crashes. Upon starting the app again and clicking on the newly created connection, everything works as expected. I am able to consistently reproduce this issue while connecting to mysql on the homestead virtual machine using vagrant and virtualbox. The size of the database doesn't seem to matter as well. Let me know if you need more info.

Good job so far on the client :+1:

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
I never tested it with a VM, I wonder if there's a connection problem with that one.
Anyway, I think this could be related to the `LibGDA` of Gnome I'm using to handle database connections.
I'm seriously thinking to drop it in favor of raw queries and standard `MySql` packages.

Can you do a test for me?
1. Create a new connection
2. Save the connection and close the modal
3. Double click on the new connection in the list to open it

Does it crash?

**Comment by stefpankov** [comment]
No, that works as expected.
However, opening the modal for a new connection, saving the connection and without closing the modal clicking on connect crashes the application.
Hope that was helpful.

**Comment by Alecaddd** [comment]
Interesting, thanks for the report, I think I did something wrong in the async method that triggers the database connection while trying to close the connection modal.
I should be able to fix it for the next release 😄
