### ISSUE TITLE
Database dropdown disabled

### ISSUE THREAD

**Issue by wout** [Alecaddd/sequeler#88]
When I connect to localhost, the database select dropdown is disabled. To enable it, I need to run a query first, any query will suffice. The UI is buggy in general because I need to hit the reload button quite often to get UI refreshes.

Using the latest version of Sequeler and elementary OS.

**Comment by Alecaddd** [comment]
Which Database are you connecting to?
PostgreSql, MySql/MariaDB?

PostgreSql comes with the dropdown disabled because of an issue with the libgda unable to get the schema table other than from the public container.

What do you mean UI is buggy? It just needs to be refreshed with the reload, or are you experiencing other glitches?

**Comment by wout** [comment]
I'm using MySQL 5.7 and created a database using the Query tab, just to check out the app. The issues I am experiencing are reproducible but not always consistent.

- many times after opening the connection, the database drop-down is inactive
- after clicking several times on the refresh button at the bottom (next to +), it becomes active
- then I can select the database but tables are not shown below
- when I hit the refresh button again several times, the tables eventually show up

From that point onward, the interface is stable. That is until I select another database because then I need to repeat the refresh process again.

But, if at any point I click the refresh button again, the database drop-down might go unselectable again. If you want I can make you a screencast illustrating the issues.

**Comment by Alecaddd** [comment]
Oh wow, that's really odd!
Thanks for the detailed report.

So, whenever you open a connection or your switched database, the app triggers a connection request to update the info, and that request is asynchronous, that means it runs in the background without affecting the UI of the app.

I wonder if something happens during this async method that prevents the UI to update at the end of it.
Thanks for the video, I can see the lag and massive delay to it, that's not normal. :thinking: 

Would you be able to test it with another database, maybe a remote database? I wonder if there's something weird going on with your local database.

Sorry for the issue, and thank you so much for using Sequeler.

**Comment by wout** [comment]
To be fair, I'm running this on a VM just to see if I can make it my default environment. So speed won't be ideal there, which might have something to do with it. Although, MySQL Workbench works fine.

At the moment I can't test any other connections because all the other servers I have access to require an SSH tunnel.

**Comment by Alecaddd** [comment]
Oh yeah, now it makes sense. I never tested it on a VM and what you're experiencing is definitely related to it.

Adding an SSH tunnel is in the backlog as I am too working with many remote DBs with SSH access.

I'm closing this issue for now as I'm not planning to optimize Sequeler for VMs.

Cheers
