### ISSUE TITLE
Content view hangs application

### ISSUE THREAD

**Issue by freaktechnik** [Alecaddd/sequeler#89]
When I select the content view for a big PgSQL table, Seqeler hangs. I assume it is trying to load too much data.

A wild guess, is that it tries to SELECT everything in the table. I'd fix this by adding a preference of a default limit of results returned that is adjustable in the settings.

**Comment by freaktechnik** [comment]
It seems there is generally an issue with results getting displayed. A SELECT query with 4 results never displayed, so I logged out and re-connected and I then got the results for my query.

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
The pagination of results limited by 500 per page is in the backlog already, that should solve the speed issues.

Regarding your second message, is your PostgreSQL server local or remote?
Does the UI freeze and you can't do anything, or simply the results don't show?
Could you share with me a dump of your DataBase table so I can import it into mine and test it?

Cheers

**Comment by freaktechnik** [comment]
> Regarding your second message, is your PostgreSQL server local or remote?

Local server

> Does the UI freeze and you can't do anything, or simply the results don't show?

The machine works hard, but I was still able to press the logout button. This works fine if I directly try to do a custom query and don't first try to see the contents of a table, so it probably has to do with freeing the previous results.

> Could you share with me a dump of your DataBase table so I can import it into mine and test it?

Sadly I can not, not only because it is huge, but also because it contains data protected under privacy laws.

**Comment by Alecaddd** [comment]
Thank you so much for the detailed answer.
I'll investigate and try to speed up the application, I'have experienced some dealy as well with big amount of data, and I need to find a better way to quickly print the results and empty the previous results.

Apologies for the issues, I'll try to improve it as soon as I can.

**Comment by Alecaddd** [comment]
The new version of Sequeler comes with Async fetch and reload, and built-in pagination of the content tab. Can you give it a try and see if you're still experiencing freezes?

**Comment by freaktechnik** [comment]
If the new version is 0.5.6 then it doesn't completely freeze the app anymore, but you have to disconnect for it to be usable again, since the result of all other queries is delayed until the long running one completes, which I have observed by errors poping up immediately when disconnecting.

If it's not 0.5.6 I'll wait for appcenter to distribute that update to me.

**Comment by Alecaddd** [comment]
Argh, unfortunately, all new versions are only available for elementary OS Juno as it relies on updated and more recent libraries. The current version is 0.6.2.
Juno is currently in Beta, but should be fully released soon. Until then, I'll keep improving the speed aspect, and also implement a `kill` option when another query gets called while another is still running.
Cheers

**Comment by freaktechnik** [comment]
Finally got around upgrading to Juno on my dev machine and restoring that database I was having trouble with. While it's much better now, I can still seemingly hang up the application by loading the content of a table that is just rows of text of variable length and switching to a different table before this query succeeded. The freeze is pretty hard - you can't even disconnect anymore. However the view tabs at the top still "work", as in the selected on is updated and the statusbar is updated, but nothing is displayed. When not switching table while it's loading you can easily switch views without any issue.

The schema of that table is `int, int, smallint, text` (octet length 1073741824). This is a postgresql db.

In fact, I haven't had it even load the first page while writing this comment.

**Comment by Alecaddd** [comment]
@freaktechnik Would you be able to pull PR #245 and check if the issue has been resolved?
