### ISSUE TITLE
Could you add a search box on the top of tables?

### ISSUE THREAD

**Issue by tomatofrommars** [Alecaddd/sequeler#92]
Is there any possibility to add a search box on the top of tables, which filter the table list instantly according to the keyword? It's very useful to find the table in hundreds of tables.
Thanks.

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
Sure, I can add that at the top of the tables list. A quick filtering while typing shouldn't be to hard to code :smile: 
Cheers

**Comment by Alecaddd** [comment]
Starting to work on this implementation for the next version.
