### ISSUE TITLE
Transparent border

### ISSUE THREAD

**Issue by jsnjack** [Alecaddd/sequeler#93]
The application has transparent border on fedora 27. Please, check the screenshot
![screenshot from 2018-03-13 21-15-13](https://user-images.githubusercontent.com/5493713/37367548-fb66e06c-2703-11e8-9852-8125f905c29c.png)

Version 0.4.3-1.fc27

**Comment by jsnjack** [comment]
The grey area around the headbar is transparent (looks like black area on my system)

**Comment by Alecaddd** [comment]
Uh, did you install from source?
The currently available release is v0.5.4
The screenshot you shared it's the old layout of the previous version

**Comment by jsnjack** [comment]
Thank you for fast response! No, I didn't. I installed if from the Software application which apparently contains an old version. I will try the version from the master branch and report back!

**Comment by jsnjack** [comment]
The layout from the master looks fine. Closing the issue. @Alecaddd , thank you for your help :)
