### ISSUE TITLE
Cant setup sqlite database

### ISSUE THREAD

**Issue by isneezy** [Alecaddd/sequeler#94]
Steps to reproduce:

1. create a new connection
2. fill out connection name and set database type to SQLite
3. try to select database file path

Observed behaviour:
When you navigate to the path where the database file resides, no file is shown

**Comment by Alecaddd** [comment]
The file chooser allows selecting only files with a `.db` extension.
Does your file have that?

If it does, can you give me more info related to the version you're running and which distro?
Cheers

**Comment by PeterNerlich** [comment]
Just got confused by this, too. Can confirm it works after renaming to `.db`.

I don't know much about these file formats, but since `.sqlite`, `.sqlite3`... and `.db` seemingly work the same or are even interchangeable?
