### ISSUE TITLE
Application claims to support opening files but does not implement g_application_open()

### ISSUE THREAD

**Issue by PeterNerlich** [Alecaddd/sequeler#97]
*Expected behavior:* Start application from command line, giving path to file as parameter → application starts normally, immediately opening connection

*Actual behaviour:* application immediately crashing, printing the following to tty:

    $ com.github.alecaddd.sequeler path/to.db
    [INFO 14:57:10.497976] Application.vala:154: Sequeler version: 0.5.4
    [INFO 14:57:10.498046] Application.vala:156: Kernel version: 4.9.18-040918-generic
    [WARNING 14:57:10.580228] [GLib-GIO] Your application claims to support opening files but does not implement g_application_open() and has no handlers connected to the 'open' signal.
    $

**Comment by Alecaddd** [comment]
Uh? That's weird, I never saw this issue.
What's your distro? GLib version?
Cheers

**Comment by Alecaddd** [comment]
Oh wait, are you trying to start the application from the terminal with the option to open a file?
If that's the case, that's not currently supported, I'm sorry.
What command you're running, and are there any specific reasons why you're not using the GUI to initialize a connection?

**Comment by PeterNerlich** [comment]
Yes, I did, because I could not see my sqlite3 database from the GUI and wanted to test what happens when I tried it that way (I found #94 afterwards immediately). I reported it because it seemed like a bug.

If this is not planned to be supported in the near future, it might for the time being be preferable to find wherever the "application claims to support opening files" and disable that, so that it just disregards the argument instead of crashing.

**Comment by Alecaddd** [comment]
All right, that makes sense.
I'll update the app to allow the selection and visualization of files with `.sqlite` and `.sqlite3` extension.

Regarding the crash and error message, the app can actually open files, in terms of importing its own exported connections file. I'm not sure how to disable or prevent that behavior from the command line, but I'll take a look at it.

Thanks for using Sequeler.
