### ISSUE TITLE
Desktop file didn't specify Exec field

### ISSUE THREAD

**Issue by wout** [Alecaddd/sequeler#98]
I was wondering if you ever plan to support non-elementaryOS distros. All elementaryOS apps are available in POP!_OS and most of them work. But with Sequeler I get the following error:

![sequeler-error](https://user-images.githubusercontent.com/107324/37839332-75aa4162-2eba-11e8-8826-46d6121ba28d.png)

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Sequeler.
I'm running it on Pop!_OS with no problems, how did you install it on it?
You can find a `.deb` file of the latest version `v0.5.4` at this URL: http://packages.elementary.io/appcenter/pool/main/c/com.github.alecaddd.sequeler/

For now, I'm not planning to actively maintain any other distro as I'm doing this in my spare time. Maybe one day next year I will do this full time, and at that point, I'll start packaging it and support other distros. But I'm not sure when.

Cheers

**Comment by wout** [comment]
Thanks for your quick reply.

I installed it using the elementaryOS store just by searching Sequeler:

![software-store](https://user-images.githubusercontent.com/107324/37840599-d3b77916-2ebd-11e8-8eec-efcf264c54db.png)

So I uninstalled it the same way and used the .deb file, which works perfectly. Many thanks!

**Comment by Alecaddd** [comment]
Oh wow! I didn't know Sequeler was available in the Software center of Pop!_OS, I wonder who submitted there, wasn't me 😄 
Well, I'm glad it works, cheers

**Comment by wout** [comment]
It wasn't available through the Pop!_Shop, I suppose it is the Flatpak store.
