### ISSUE TITLE
crashing when executing a query

### ISSUE THREAD

**Issue by rezk2ll** [Alecaddd/sequeler#99]
whenever i try to execute a `select` query on a `mysql` database ( of a drupal project ) the app crashes, i tried launching it via the console to figure out why and here is what i got:

```
[INFO 10:11:58.158536] Application.vala:154: Sequeler version: 0.5.4
[INFO 10:11:58.158623] Application.vala:156: Kernel version: 4.13.0-37-generic
[WARNING 10:11:58.178680] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-nlZ48f7fnf: Connection refused
[WARNING 10:12:11.283940] [Gtk] /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkliststore.c:836: Unable to convert from GdaNull to GdaBlob
[FATAL 10:12:11.301684] [Gtk] gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
[1]    21124 segmentation fault (core dumped)  com.github.alecaddd.sequeler
```

any idea why is this happening? and how can i fix it?

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler.
Unfortunately, that's a known issue of the `LibGDA` library I'm using to handle different database connections. It's a bit outdated and has these bugs that cause the app to crash when the data in the cell doesn't perfectly match the datatype of the column.

Recently, `LibGDA` was forked and ported to GitLab, and hopefully, we can expect a new version with improvements and fixes soon.
If that doesn't happen, I'm planning to refactor Sequeler to not use that library and rely on regular, built-in database libraries.

Cheers

**Comment by Alecaddd** [comment]
@rezk2ll Could you test the latest version of Sequeler and see if this issue have been solved?

**Comment by Alecaddd** [comment]
Any updates on this issue?

**Comment by Alecaddd** [comment]
Closing this for lack of updates
